// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
  children: [
    JsxRuntime.jsxs("p", {
      children: [
        "The possessive adjective consists of a prefix (object owned) and a suffix (the owner). For Class 1, the singular prefix is ",
        JsxRuntime.jsx("strong", {
          children: "wa-"
        }),
        " and the plural is ",
        JsxRuntime.jsx("strong", {
          children: "ba-"
        }),
        "."
      ]
    }),
    JsxRuntime.jsxs("table", {
      children: [
        JsxRuntime.jsx("thead", {
          children: JsxRuntime.jsxs("tr", {
            children: [
              JsxRuntime.jsx("th", {
                children: "Suffix"
              }),
              JsxRuntime.jsx("th", {
                children: "Singular (wa-)"
              }),
              JsxRuntime.jsx("th", {
                children: "Plural (ba-)"
              })
            ]
          })
        }),
        JsxRuntime.jsxs("tbody", {
          children: [
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-nje (me)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wanje (my)"
                }),
                JsxRuntime.jsx("td", {
                  children: "banje (my)"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-we (you sing.)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wawe (your)"
                }),
                JsxRuntime.jsx("td", {
                  children: "bawe (your)"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-iwe (him/her)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wiwe (his/hers)"
                }),
                JsxRuntime.jsx("td", {
                  children: "biwe (his/hers)"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-cu (us)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wacu (our)"
                }),
                JsxRuntime.jsx("td", {
                  children: "bacu (our)"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-nyu (you pl.)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wanyu (your)"
                }),
                JsxRuntime.jsx("td", {
                  children: "banyu (your)"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "-bo (them)"
                }),
                JsxRuntime.jsx("td", {
                  children: "wabo (their)"
                }),
                JsxRuntime.jsx("td", {
                  children: "babo (their)"
                })
              ]
            })
          ]
        })
      ],
      className: "min-w-full divide-y"
    }),
    JsxRuntime.jsxs("p", {
      children: [
        JsxRuntime.jsx("strong", {
          children: "Note:"
        }),
        " The 3rd person singular contracts: wa-iwe = wiwe, ba-iwe = biwe. The possessive regularly follows the noun it modifies."
      ],
      style: {
        marginTop: "1rem"
      }
    }),
    JsxRuntime.jsxs("p", {
      children: [
        JsxRuntime.jsx("strong", {
          children: "Mbega:"
        }),
        " Introduces a question but is not translated. It elides before a vowel (e.g., Mbeg' abigishwa...)."
      ]
    })
  ]
});

let l_vocabulary = [
  [
    "umūntu",
    "person (nasalized 'ntu')"
  ],
  [
    "umukozi",
    "workman, employee"
  ],
  [
    "umutāma",
    "old man"
  ],
  [
    "Umukiza",
    "Savior"
  ],
  [
    "aravuga",
    "he/she is speaking"
  ],
  [
    "egome",
    "yes (emphatic)"
  ],
  [
    "oyaye",
    "no (emphatic)"
  ]
];

let l_examples = [
  [
    "umwana wanje",
    "my child"
  ],
  [
    "abana biwe",
    "his children"
  ],
  [
    "abana babo",
    "their children"
  ],
  [
    "Mbeg’ abigishwa bararima?",
    "Are the pupils hoeing?"
  ]
];

let l_quiz = [
  {
    title: "I. Translate into English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "1. Umukiza wacu ni Yesu.",
        answer: "Our Savior is Jesus"
      },
      {
        TAG: "MultipleChoice",
        prompt: "2. Umwigisha wabo aravuga.",
        options: [
          "Their teacher is speaking",
          "Our teacher is speaking",
          "Their teacher is working"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "3. Abakozi banyu bararima.",
        answer: "Your workers are hoeing"
      },
      {
        TAG: "PartialInput",
        prompt: "4. Umwana wawe n’umuhungu.",
        answer: "Your child is a boy",
        hint: "wawe indicates singular 'your'"
      },
      {
        TAG: "TextInput",
        prompt: "5. Abigishwa babo barakora.",
        answer: "Their pupils are working"
      },
      {
        TAG: "TextInput",
        prompt: "6. Abantu barakora cane.",
        answer: "The people are working hard"
      },
      {
        TAG: "MultipleChoice",
        prompt: "7. Mbeg’ umwigisha wanyu ararima?",
        options: [
          "Is my teacher hoeing?",
          "Is your teacher hoeing?",
          "Are the teachers hoeing?"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "8. Abana banje n’abakobwa.",
        answer: "My children are girls"
      }
    ]
  },
  {
    title: "II. Translate into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "1. My child.",
        answer: "Umwana wanje"
      },
      {
        TAG: "TextInput",
        prompt: "2. Your (sing.) husband.",
        answer: "Umugabo wawe"
      },
      {
        TAG: "MultipleChoice",
        prompt: "3. His workmen.",
        options: [
          "Abakozi biwe",
          "Abakozi babo",
          "Umukozi wiwe"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "4. Your (pl.) teachers.",
        answer: "Abigisha banyu"
      },
      {
        TAG: "TextInput",
        prompt: "5. Your (sing.) children.",
        answer: "Abana bawe"
      },
      {
        TAG: "PartialInput",
        prompt: "6. Her pupils.",
        answer: "Abigishwa biwe",
        hint: "Use the plural 'ba' prefix for the possessive"
      },
      {
        TAG: "TextInput",
        prompt: "7. Our Savior.",
        answer: "Umukiza wacu"
      },
      {
        TAG: "TextInput",
        prompt: "8. Our boys.",
        answer: "Abahungu bacu"
      },
      {
        TAG: "MultipleChoice",
        prompt: "9. Their wives.",
        options: [
          "Abagore banje",
          "Abagore babo",
          "Abagore banyu"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "10. Your (pl.) girls.",
        answer: "Abakobwa banyu"
      },
      {
        TAG: "MultipleChoice",
        prompt: "11. The old men work (are working).",
        options: [
          "Abasaza barakora",
          "Umusage arakora",
          "Abasaza bararima"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "12. Your (pl.) king.",
        answer: "Umwami wanyu"
      },
      {
        TAG: "TextInput",
        prompt: "13. Our children are hoeing.",
        answer: "Abana bacu bararima"
      },
      {
        TAG: "PartialInput",
        prompt: "14. Your (pl.) children are girls.",
        answer: "Abana banyu n'abakobwa",
        hint: "Remember the conjunction 'n'' for 'are'"
      },
      {
        TAG: "TextInput",
        prompt: "15. My sons are not pupils.",
        answer: "Abahungu banje si abigishwa"
      }
    ]
  }
];

let l = {
  title: "LESSON 3: Possessive Adjectives",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
