// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs("div", {
  children: [
    JsxRuntime.jsx("p", {
      children: "Class 3: The prefix for Class 3 is in- for both singular and plural. The context and agreements will usually indicate whether the word is singular or plural. Later we will note some variations of this prefix.",
      className: "text-gray-700 leading-relaxed"
    }),
    JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h3", {
          children: "Possessive Adjective Prefixes",
          className: "text-xl font-semibold text-blue-800"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsxs("table", {
            children: [
              JsxRuntime.jsx("thead", {
                children: JsxRuntime.jsxs("tr", {
                  children: [
                    JsxRuntime.jsx("th", {
                      children: "Number",
                      className: "px-4 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider border-r border-gray-300"
                    }),
                    JsxRuntime.jsx("th", {
                      children: "Prefix",
                      className: "px-4 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider border-r border-gray-300"
                    }),
                    JsxRuntime.jsx("th", {
                      children: "Example",
                      className: "px-4 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider border-r border-gray-300"
                    }),
                    JsxRuntime.jsx("th", {
                      children: "Meaning",
                      className: "px-4 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider"
                    })
                  ]
                }),
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tbody", {
                children: [
                  JsxRuntime.jsxs("tr", {
                    children: [
                      JsxRuntime.jsx("td", {
                        children: "Singular",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "ya-",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "inka yanje",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "my cow",
                        className: "px-4 py-3 text-sm text-gray-800"
                      })
                    ],
                    className: "hover:bg-gray-50"
                  }),
                  JsxRuntime.jsxs("tr", {
                    children: [
                      JsxRuntime.jsx("td", {
                        children: "Plural",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "za-",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "inka zanje",
                        className: "px-4 py-3 text-sm text-gray-800 border-r border-gray-300"
                      }),
                      JsxRuntime.jsx("td", {
                        children: "my cows",
                        className: "px-4 py-3 text-sm text-gray-800"
                      })
                    ],
                    className: "hover:bg-gray-50"
                  })
                ],
                className: "bg-white divide-y divide-gray-200"
              })
            ],
            className: "min-w-full divide-y divide-gray-200 border border-gray-300"
          }),
          className: "overflow-x-auto"
        })
      ],
      className: "space-y-3"
    }),
    JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h3", {
          children: "Consonant Change Rules",
          className: "text-xl font-semibold text-blue-800"
        }),
        JsxRuntime.jsx("p", {
          children: "Memorize these rules, they are used in many words:",
          className: "text-gray-600 italic"
        }),
        JsxRuntime.jsxs("ul", {
          children: [
            JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "n before labials (b, m, v, f, p) → m",
                  className: "font-medium text-gray-900"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    "Example: ",
                    JsxRuntime.jsx("code", {
                      children: "imbwa (in-bwa)",
                      className: "bg-gray-100 px-2 py-1 rounded text-sm font-mono"
                    })
                  ],
                  className: "ml-4 text-gray-600"
                })
              ]
            }),
            JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "n + h → mp",
                  className: "font-medium text-gray-900"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    "Example: ",
                    JsxRuntime.jsx("code", {
                      children: "impuzu (in-huzu)",
                      className: "bg-gray-100 px-2 py-1 rounded text-sm font-mono"
                    })
                  ],
                  className: "ml-4 text-gray-600"
                })
              ]
            }),
            JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "n + r → nd",
                  className: "font-medium text-gray-900"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    "Example: ",
                    JsxRuntime.jsx("code", {
                      children: "indimiro (in-rimiro)",
                      className: "bg-gray-100 px-2 py-1 rounded text-sm font-mono"
                    })
                  ],
                  className: "ml-4 text-gray-600"
                })
              ]
            }),
            JsxRuntime.jsx("li", {
              children: JsxRuntime.jsx("span", {
                children: "n before another n drops out",
                className: "font-medium text-gray-900"
              })
            }),
            JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "n before a vowel root → nz",
                  className: "font-medium text-gray-900"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    "Example: ",
                    JsxRuntime.jsx("code", {
                      children: "inzara (in-ara)",
                      className: "bg-gray-100 px-2 py-1 rounded text-sm font-mono"
                    })
                  ],
                  className: "ml-4 text-gray-600"
                })
              ]
            })
          ],
          className: "space-y-3 pl-5 list-disc text-gray-700"
        })
      ],
      className: "space-y-3"
    }),
    JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                clipRule: "evenodd",
                d: "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z",
                fillRule: "evenodd"
              }),
              className: "h-5 w-5 text-blue-400",
              fill: "currentColor",
              viewBox: "0 0 20 20"
            }),
            className: "flex-shrink-0"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsxs("p", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "Note: ",
                  className: "font-medium"
                }),
                "In the word ",
                JsxRuntime.jsx("code", {
                  children: "Imana (in-mana)",
                  className: "bg-blue-100 px-1 py-0.5 rounded text-sm font-mono"
                }),
                " the n drops out before m, thus making Imana."
              ],
              className: "text-sm text-blue-700"
            }),
            className: "ml-3"
          })
        ],
        className: "flex"
      }),
      className: "bg-blue-50 border-l-4 border-blue-400 p-4 rounded-r"
    })
  ],
  className: "space-y-6"
});

let l_vocabulary = [
  [
    "inka",
    "cow"
  ],
  [
    "Imana",
    "God"
  ],
  [
    "imbwa",
    "dog"
  ],
  [
    "impūzu",
    "clothes"
  ],
  [
    "indimiro",
    "field"
  ],
  [
    "inzu",
    "house, room"
  ],
  [
    "intebe",
    "chair, stool"
  ]
];

let l_examples = [
  [
    "inka yanje",
    "my cow (singular possessive)"
  ],
  [
    "inka zanje",
    "my cows (plural possessive)"
  ],
  [
    "imbwa (in-bwa)",
    "dog (n before labial → m)"
  ],
  [
    "impuzu (in-huzu)",
    "clothes (n + h → mp)"
  ],
  [
    "indimiro (in-rimiro)",
    "field (n + r → nd)"
  ],
  [
    "Imana (in-mana)",
    "God (n before m drops out)"
  ],
  [
    "inzara (in-ara)",
    "hunger (n before vowel → nz)"
  ]
];

let l_quiz = [
  {
    title: "I. Translate from Kirundi to English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Inka z’umugabo.",
        answer: "The man's cows."
      },
      {
        TAG: "TextInput",
        prompt: "Umutama n’imbwa yiwe.",
        answer: "The child and his dog."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Umuhungu akora mu ndimiro yiwe.",
        options: [
          "The boy works in his field.",
          "The girl works in her field.",
          "The boy is playing in his field.",
          "The boy works in the house."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Abakobwa bafise intebe zabo.",
        answer: "The girls have their chairs."
      },
      {
        TAG: "TextInput",
        prompt: "Umukobwa afise impuzu mu nzu yanje.",
        answer: "The girl has clothes in my house."
      },
      {
        TAG: "TextInput",
        prompt: "Umwana afise impuzu zawe.",
        answer: "The child has your clothes."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Inka zawe ziri mu murima wanje.",
        options: [
          "Your cows are in my field.",
          "My cows are in your field.",
          "The cows are in the field.",
          "Your cows are in the house."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Abantu bagenda mu nzu.",
        answer: "The people are going into the house."
      }
    ]
  },
  {
    title: "II. Translate from English to Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "The men’s houses.",
        answer: "Inzu z’abagabo."
      },
      {
        TAG: "TextInput",
        prompt: "The girl’s chair.",
        answer: "Intebe y’umukobwa."
      },
      {
        TAG: "MultipleChoice",
        prompt: "I have a dog.",
        options: [
          "Mfise imbwa.",
          "Mfise inka.",
          "Ndagira imbwa.",
          "Mfise umugabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Our chairs.",
        answer: "Intebe zacu."
      },
      {
        TAG: "TextInput",
        prompt: "Their cows.",
        answer: "Inka zabo."
      },
      {
        TAG: "PartialInput",
        prompt: "My God in Kirundi is: Imana ______",
        answer: "yanje",
        hint: "possessive suffix for 'my'"
      },
      {
        TAG: "TextInput",
        prompt: "Your (pl.) clothes.",
        answer: "Impuzu zanyu."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The old man’s cows.",
        options: [
          "Inka z’umusaza.",
          "Inka z’umugabo.",
          "Inka z’umukobwa.",
          "Inka z’abagabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The teachers’ children.",
        answer: "Abana b’abarimu."
      },
      {
        TAG: "TextInput",
        prompt: "The woman’s clothes.",
        answer: "Impuzu z’umugore."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The children are going into the man’s field.",
        options: [
          "Abana bagenda mu murima w’umugabo.",
          "Abagore bagenda mu murima w’umugabo.",
          "Abana bagenda mu nzu y’umugabo.",
          "Abana bafise mu murima w’umugabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "PartialInput",
        prompt: "I am working in the teacher’s field. → Nkora mu murima ______",
        answer: "w’umwarimu",
        hint: "possessive form for 'teacher'"
      },
      {
        TAG: "TextInput",
        prompt: "The women have bread on their heads.",
        answer: "Abagore bafise umugati mu mitwe yabo."
      }
    ]
  }
];

let l = {
  title: "LESSON 7: Class 3 in–, in–",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
