// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs("p", {
  children: [
    "The possessive particle expresses 'of' or '-'s'. It follows the noun being possessed and must agree with that noun's class prefix. Note: the final '-a' elides (drops) before a following vowel, becoming w', b', or y'.",
    JsxRuntime.jsx("br", {}),
    JsxRuntime.jsx("br", {}),
    "Class 1: Singular (wa), Plural (ba)",
    JsxRuntime.jsx("br", {}),
    "Class 2: Singular (wa), Plural (ya)"
  ]
});

let l_vocabulary = [
  [
    "umushatsi",
    "hair"
  ],
  [
    "umugozi",
    "string, rope"
  ],
  [
    "umugisha",
    "blessing"
  ],
  [
    "umurima",
    "garden"
  ],
  [
    "ndagenda",
    "I am going, I go"
  ],
  [
    "ndakora",
    "I am working, I work"
  ],
  [
    "mfise",
    "I have"
  ]
];

let l_examples = [
  [
    "Umutima wa Yesu",
    "The heart of Jesus (Jesus' heart)"
  ],
  [
    "Imirima y'abantu",
    "The gardens of the people (people's gardens)"
  ],
  [
    "Abana b'umwigisha",
    "The teacher's children"
  ]
];

let l_quiz = [
  {
    title: "I. Plurals and Meanings",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Make plural: Umwana w’umwami (The king's child)",
        answer: "Abana b’abami"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Make plural: Umutwe w’umuntu (The person's head)",
        options: [
          "Amitwe y'abantu",
          "Imitwe y’abantu",
          "Imitwe w'abantu"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "Make plural: Umurima w’umutama (The old man's garden)",
        answer: "Imirima y’abatama"
      },
      {
        TAG: "PartialInput",
        prompt: "Make plural: Umugore w’umugabo (The man's wife)",
        answer: "Abagore b’abagabo",
        hint: "Use Class 2 plurals."
      },
      {
        TAG: "TextInput",
        prompt: "Make plural: Umuhungu w’umwigisha (The teacher's son)",
        answer: "Abahungu b’abigisha"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Make plural: Umwigishwa wa Paulo (Paul's disciple)",
        options: [
          "Abigishwa ba Paulo",
          "Abigishwa ya Paulo",
          "Imigishwa ba Paulo"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Make plural: Umugozi w’umuhungu (The boy's rope)",
        answer: "Imigozi y’abahungu"
      },
      {
        TAG: "TextInput",
        prompt: "Make plural: Umwenda w’umukozi (The worker's garment)",
        answer: "Imyenda y’abakozi"
      },
      {
        TAG: "PartialInput",
        prompt: "Make plural: Umwami w’abantu (The king of the people)",
        answer: "Abami b’abantu",
        hint: "Note that 'abantu' is already plural."
      },
      {
        TAG: "TextInput",
        prompt: "Make plural: Umutima w’umuntu (The person's heart)",
        answer: "Imitima y’abantu"
      }
    ]
  },
  {
    title: "II. Translation into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "The people of Jesus have joy in their hearts.",
        answer: "Abantu ba Yezu bafise akanyamuneza mu mitima yabo"
      },
      {
        TAG: "PartialInput",
        prompt: "I have the light of Jesus in my heart.",
        answer: "Mfise umuco wa Yezu mu mutima wanje",
        hint: "Umuco = Light."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The teacher’s workmen are working in his gardens.",
        options: [
          "Abakozi b'umwigisha bariko barakora mu mirima yiwe",
          "Umukozi w'umwigisha ariko arakora mu mirima yiwe",
          "Abakozi b'umwigisha bafise imirima yiwe"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The child of the king is a girl.",
        answer: "Umwana w’umwami ni umwigeme"
      },
      {
        TAG: "TextInput",
        prompt: "The smoke of the fire.",
        answer: "Umwotsi w’umuriro"
      },
      {
        TAG: "MultipleChoice",
        prompt: "I work on our hill.",
        options: [
          "Ndakora ku mugasozi wanyu",
          "Ndakora ku mugasozi wacu",
          "Barakora ku mugasozi wacu"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "The child has hair.",
        answer: "Umwana afise imishatsi"
      },
      {
        TAG: "PartialInput",
        prompt: "I am working in the darkness.",
        answer: "Ndiko ndakora mu muzimagiza",
        hint: "Darkness = Umuzimagiza."
      },
      {
        TAG: "TextInput",
        prompt: "I am going to the teacher’s garden.",
        answer: "Ngira mu murima w’umwigisha"
      },
      {
        TAG: "MultipleChoice",
        prompt: "The old man has the blessing of the Savior in his heart.",
        options: [
          "Umutama afise umuhezagiro w’Umukiza mu mutima wiwe",
          "Umuhungu afise umuhezagiro w’Umukiza mu mutima wiwe",
          "Umutama afise umuco w’Umukiza mu mutima wiwe"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Jesus is my Lord and Savior.",
        answer: "Yezu ni Umwami wanje n’Umukiza wanje"
      }
    ]
  }
];

let l = {
  title: "LESSON 6: Possessive Particle",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
