// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
  children: [
    JsxRuntime.jsx("p", {
      children: "Class 2 is used for inanimate objects and non-human nouns. While the singular prefix (umu-) is identical to Class 1, you can distinguish them by the plural prefix (imi-) and the context: if it is not a person, it is Class 2."
    }),
    JsxRuntime.jsx("h3", {
      children: "Prefixes and Possessives"
    }),
    JsxRuntime.jsxs("table", {
      children: [
        JsxRuntime.jsx("thead", {
          children: JsxRuntime.jsxs("tr", {
            children: [
              JsxRuntime.jsx("th", {
                children: "Number"
              }),
              JsxRuntime.jsx("th", {
                children: "Noun Prefix"
              }),
              JsxRuntime.jsx("th", {
                children: "Possessive Prefix"
              })
            ]
          })
        }),
        JsxRuntime.jsxs("tbody", {
          children: [
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "Singular"
                }),
                JsxRuntime.jsx("td", {
                  children: "umu-"
                }),
                JsxRuntime.jsx("td", {
                  children: "wa-"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "Plural"
                }),
                JsxRuntime.jsx("td", {
                  children: "imi-"
                }),
                JsxRuntime.jsx("td", {
                  children: "ya-"
                })
              ]
            })
          ]
        })
      ]
    }),
    JsxRuntime.jsx("h3", {
      children: "The Conjunction 'na'"
    }),
    JsxRuntime.jsx("p", {
      children: "The word 'na' (and) joins nouns but not clauses. It elides to 'n\'' before words beginning with a vowel. Note that in Kirundi, 'na' must be repeated between every item in a series."
    })
  ]
});

let l_vocabulary = [
  [
    "umutima",
    "heart"
  ],
  [
    "umusozi",
    "hill, mountain"
  ],
  [
    "umuriro",
    "fire (no pl.)"
  ],
  [
    "nēza",
    "well (adv.), nicely"
  ],
  [
    "umucanwa",
    "fire (as in fireplace, no pl.)"
  ],
  [
    "na",
    "and, with, by"
  ],
  [
    "umutsima",
    "bread (native doughy porridge)"
  ],
  [
    "umūnyu",
    "salt"
  ],
  [
    "umutwe",
    "head"
  ]
];

let l_examples = [
  [
    "umutwe wiwe",
    "his head"
  ],
  [
    "imitwe yabo",
    "their heads"
  ],
  [
    "umugabo n'umugore",
    "a man and a woman"
  ],
  [
    "umugabo n'umugore n'umwana",
    "a man, woman, and child"
  ]
];

let l_quiz = [
  {
    title: "I. Plurals and Meanings",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Give the plural and meaning for: umukozi wawe",
        answer: "abakozi banyu: your workers"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Give the plural and meaning for: umutima wiwe",
        options: [
          "imitima yabo: their hearts",
          "abana babo: their children",
          "imitima yiwe: his hearts",
          "umutima wabo: their heart"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Give the plural and meaning for: umwana wabo",
        answer: "abana babo: their children"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Give the plural and meaning for: umusozi wacu",
        options: [
          "imisozi yacu: our mountains",
          "abasozi wacu: our mountain",
          "imisozi yabo: their mountains",
          "umusozi wacu: our mountain"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Give the plural and meaning for: umutsima wanje",
        answer: "imitsima yacu: our bread"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Give the plural and meaning for: umutwe wawe",
        options: [
          "imitwe yanyu: your heads",
          "abanywa banyu: your mouths",
          "imitwe wawe: your head",
          "umutwe yanyu: your heads"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Give the plural and meaning for: umwigishwa wiwe",
        answer: "abigishwa babo: their pupils"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Give the plural and meaning for: umukobwa wanje",
        options: [
          "abakobwa bacu: our daughters",
          "abakobwa wanje: my daughters",
          "imikobwa yacu: our girls",
          "abakobwa banyu: your daughters"
        ],
        correctIndex: 0
      }
    ]
  },
  {
    title: "II. Translate into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "The boy and the girl have their bread.",
        answer: "Umuhungu n’umukobwa bafise umutsima wabo"
      },
      {
        TAG: "TextInput",
        prompt: "Jesus is my Savior.",
        answer: "Yezu ni Umukiza wanje"
      },
      {
        TAG: "TextInput",
        prompt: "The old man has salt and bread.",
        answer: "Umusaza afise umunyu n’umutsima"
      },
      {
        TAG: "TextInput",
        prompt: "Your (pl.) children work well.",
        answer: "Abana banyu barakora neza"
      },
      {
        TAG: "MultipleChoice",
        prompt: "His daughter and your (sing.) son are going.",
        options: [
          "Umukobwa wiwe n’umuhungu wawe baragenda",
          "Umukobwa wabo n’umuhungu wacu baragenda",
          "Abakobwa biwe n’umuhungu wawe baragenda",
          "Umukobwa wiwe n’umuhungu wawe barakora"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "My teacher has a fire.",
        answer: "Umwigisha wanje afise umuriro"
      },
      {
        TAG: "MultipleChoice",
        prompt: "The workmen and the pupils are hoeing.",
        options: [
          "Abakozi n’abigishwa bararima",
          "Umukozi n’umwigishwa bararima",
          "Abakozi n’abigishwa barakora",
          "Abakozi n’abigishwa baragenda"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The people are speaking.",
        answer: "Abantu baravuga"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Your (pl.) teachers have (some) salt.",
        options: [
          "Abigisha banyu bafise umunyu",
          "Umwigisha wanyu afise umunyu",
          "Abigisha bacu bafise umunyu",
          "Abigisha banyu bafise umutsima"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The workman has his bread and (some) salt.",
        answer: "Umukozi afise umutsima wiwe n’umunyu"
      },
      {
        TAG: "PartialInput",
        prompt: "Is your (pl.) child a boy? No, it’s a girl.",
        answer: "Umwana wanyu ni umuhungu? Oya, ni umukobwa",
        hint: "Start with the question about the child's gender."
      }
    ]
  }
];

let l = {
  title: "LESSON 4: Class 2 umu–, imi–",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
