// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs("div", {
  children: [
    JsxRuntime.jsx("p", {
      children: JsxRuntime.jsx("strong", {
        children: "16. Vowel changes."
      })
    }),
    JsxRuntime.jsxs("ul", {
      children: [
        JsxRuntime.jsxs("li", {
          children: [
            JsxRuntime.jsx("strong", {
              children: "(a)"
            }),
            " Though in Par. 3 we stated that 'a' before another vowel drops out, there are exceptions to this rule. In the adjectives –iza and –inshi, when an 'a' precedes the 'i', the two contract into e, thus:",
            JsxRuntime.jsx("br", {}),
            "ba-iza becomes beza, ba-inshi becomes benshi"
          ]
        }),
        JsxRuntime.jsxs("li", {
          children: [
            JsxRuntime.jsx("strong", {
              children: "(b)"
            }),
            " Remember that as stated in Par. 3, 'u' before another vowel becomes 'w', thus:",
            JsxRuntime.jsx("br", {}),
            "mu-iza becomes mwiza"
          ]
        }),
        JsxRuntime.jsxs("li", {
          children: [
            JsxRuntime.jsx("strong", {
              children: "(c)"
            }),
            " Also remember that 'i' often (not always) becomes 'y' before another vowel, thus:",
            JsxRuntime.jsx("br", {}),
            "mi-iza becomes myiza, mi-inshi becomes myinshi"
          ]
        })
      ]
    }),
    JsxRuntime.jsxs("p", {
      children: [
        JsxRuntime.jsx("strong", {
          children: "Note I:"
        }),
        " In Par. 14 we said that 'n' before a vowel becomes 'nz', thus: n-iza becomes nziza; however, the adjective –inshi is an exception, for n-inshi becomes nyinshi."
      ]
    }),
    JsxRuntime.jsxs("table", {
      children: [
        JsxRuntime.jsx("thead", {
          children: JsxRuntime.jsxs("tr", {
            children: [
              JsxRuntime.jsx("th", {
                children: "Class"
              }),
              JsxRuntime.jsx("th", {
                children: "-iza forms"
              }),
              JsxRuntime.jsx("th", {
                children: "-inshi forms"
              })
            ]
          })
        }),
        JsxRuntime.jsxs("tbody", {
          children: [
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "Class 1:"
                }),
                JsxRuntime.jsx("td", {
                  children: "mwiza, beza"
                }),
                JsxRuntime.jsx("td", {
                  children: "mwinshi, benshi"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "Class 2:"
                }),
                JsxRuntime.jsx("td", {
                  children: "mwiza, myiza"
                }),
                JsxRuntime.jsx("td", {
                  children: "mwinshi, myinshi"
                })
              ]
            }),
            JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                  children: "Class 3:"
                }),
                JsxRuntime.jsx("td", {
                  children: "nziza, nziza"
                }),
                JsxRuntime.jsx("td", {
                  children: "nyinshi, nyinshi"
                })
              ]
            })
          ]
        })
      ]
    }),
    JsxRuntime.jsxs("p", {
      children: [
        JsxRuntime.jsx("strong", {
          children: "Note II:"
        }),
        " The adjective nini in agreeing with the 3rd class does not get an extra n. It is simply like the stem: inka nini – a big cow."
      ]
    }),
    JsxRuntime.jsxs("p", {
      children: [
        JsxRuntime.jsx("strong", {
          children: "Note III:"
        }),
        " The adjectives –nini and –to may be reduplicated in the plural forms: abahungu banini-banini – big boys, abana bato-bato – little children."
      ]
    })
  ]
});

let l_vocabulary = [];

let l_examples = [
  [
    "inka nini",
    "a big cow"
  ],
  [
    "abahungu banini-banini",
    "big boys"
  ],
  [
    "abana bato-bato",
    "little children"
  ],
  [
    "ba-iza",
    "beza"
  ],
  [
    "ba-inshi",
    "benshi"
  ],
  [
    "mu-iza",
    "mwiza"
  ],
  [
    "mi-iza",
    "myiza"
  ],
  [
    "mi-inshi",
    "myinshi"
  ],
  [
    "n-iza",
    "nziza"
  ],
  [
    "n-inshi",
    "nyinshi"
  ]
];

let l_quiz = [
  {
    title: "I. Translate into English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Inka ziwe ni nyinshi.",
        answer: "His cows are many."
      },
      {
        TAG: "TextInput",
        prompt: "Afise umwana mwiza.",
        answer: "He has a beautiful child."
      },
      {
        TAG: "TextInput",
        prompt: "Umukobwa wiwe n’umuhungu wiwe ni batoya.",
        answer: "His daughter and his son are small."
      },
      {
        TAG: "TextInput",
        prompt: "Inzu zabo nini ni nziza cane.",
        answer: "Their large house is very beautiful."
      },
      {
        TAG: "TextInput",
        prompt: "Abana bato si babi.",
        answer: "Small children are not bad."
      },
      {
        TAG: "TextInput",
        prompt: "Umugabo muremure akora mu ndimiro y’umwigisha.",
        answer: "A tall man works in the teacher's garden."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Mfise intebe nziza nshasha.",
        options: [
          "I have a beautiful new chair.",
          "He has a beautiful new chair.",
          "They have a beautiful new chair."
        ],
        correctIndex: 0
      },
      {
        TAG: "MultipleChoice",
        prompt: "Umuhungu mutoya afise umunyu mwinshi.",
        options: [
          "A small boy has much salt.",
          "A tall boy has much salt.",
          "A small boy has many cows."
        ],
        correctIndex: 0
      },
      {
        TAG: "MultipleChoice",
        prompt: "Mbeg’ abigishwa bafise impuzu nziza?",
        options: [
          "Do the students have nice clothes?",
          "Does the teacher have nice clothes?",
          "Are the students nice?"
        ],
        correctIndex: 0
      },
      {
        TAG: "PartialInput",
        prompt: "Mbeg’ inka z’umutama ni nini?",
        answer: "Are the farmer's cows large?",
        hint: "This is a question about the size of the farmer's cows."
      }
    ]
  },
  {
    title: "II. Translate into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "My good dog is very short.",
        answer: "Inja yanjye nziza ni igufi cane."
      },
      {
        TAG: "TextInput",
        prompt: "Your (pl.) large houses are nice.",
        answer: "Inzo zanyu nini ni nziza."
      },
      {
        TAG: "TextInput",
        prompt: "Our small chairs are new.",
        answer: "Intebe zacu ntoya ni nshasha."
      },
      {
        TAG: "TextInput",
        prompt: "Our great God is good.",
        answer: "Imana yacu nini ni nziza."
      },
      {
        TAG: "TextInput",
        prompt: "Your (pl.) many people work hard.",
        answer: "Abantu banyu benshi bakora cane."
      },
      {
        TAG: "TextInput",
        prompt: "A tall man is walking in the garden.",
        answer: "Umugabo muremure aragenda mu ndimiro."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The good children are not few.",
        options: [
          "Abana nziza si bake.",
          "Abana bato si bake.",
          "Abana benshi si bake."
        ],
        correctIndex: 0
      },
      {
        TAG: "MultipleChoice",
        prompt: "The teacher has many gardens.",
        options: [
          "Umwigisha afise indimiro nyinshi.",
          "Umwigisha afise inka nyinshi.",
          "Abigishwa bafise indimiro nyinshi."
        ],
        correctIndex: 0
      },
      {
        TAG: "MultipleChoice",
        prompt: "His long string is nice.",
        options: [
          "Umugozi wiwe muremure ni nziza.",
          "Umugozi wiwe mutoya ni nziza.",
          "Umuhungu wiwe muremure ni nziza."
        ],
        correctIndex: 0
      },
      {
        TAG: "PartialInput",
        prompt: "Our God is living.",
        answer: "Imana yacu iri kubaho.",
        hint: "Use 'iri kubaho' for 'is living'."
      }
    ]
  }
];

let l = {
  title: "LESSON 9: Adjectives (continued)",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
