// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
  children: [
    JsxRuntime.jsx("h3", {
      children: "1. Vowel Change Rules"
    }),
    JsxRuntime.jsxs("p", {
      children: [
        "The singular prefix of Class 1 is 'umu', but it appears as 'umw' when the stem begins with a vowel. This is because ",
        JsxRuntime.jsx("strong", {
          children: "u"
        }),
        " before another vowel becomes ",
        JsxRuntime.jsx("strong", {
          children: "w"
        }),
        ". This change often lengthens the following vowel."
      ]
    }),
    JsxRuntime.jsxs("p", {
      children: [
        "Similarly, ",
        JsxRuntime.jsx("strong", {
          children: "a"
        }),
        " before another vowel drops out (elision). For example: aba-ana becomes abāna."
      ]
    }),
    JsxRuntime.jsx("h3", {
      children: "2. Use of Ni and Si"
    }),
    JsxRuntime.jsx("p", {
      children: "'Ni' (is/are) and 'Si' (is not/are not) are used for states of being. They do not change form based on number (singular or plural)."
    }),
    JsxRuntime.jsxs("ul", {
      children: [
        JsxRuntime.jsx("li", {
          children: "The 'i' elides before a vowel (e.g., Ni + umwami = N'umwami)."
        }),
        JsxRuntime.jsx("li", {
          children: "Do not elide before a proper noun."
        }),
        JsxRuntime.jsx("li", {
          children: "Do not use these for locations (unless the subject itself is a place)."
        })
      ]
    })
  ]
});

let l_vocabulary = [
  [
    "umwāna (pl. abāna)",
    "child"
  ],
  [
    "umwāmi (abāmi)",
    "king, Lord"
  ],
  [
    "umwīgīsha (abīgīsha)",
    "teacher"
  ],
  [
    "umwīgīshwa (abīgīshwa)",
    "pupil"
  ],
  [
    "afise",
    "he/she has"
  ],
  [
    "bafise",
    "they have"
  ],
  [
    "cane",
    "much, very"
  ],
  [
    "urakoze",
    "thank you"
  ]
];

let l_examples = [
  [
    "N’umwami",
    "It is the king"
  ],
  [
    "Umwana n’umukobwa",
    "The child is a girl"
  ],
  [
    "Umugabo s’umwami",
    "The man is not a king"
  ],
  [
    "Umwigisha ni Andereya",
    "The teacher is Andrew"
  ],
  [
    "Gitega ni kure",
    "Gitega is far away"
  ]
];

let l_quiz = [
  {
    title: "I. Plurals and Meanings",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Plural of 'umwana' and its meaning:",
        answer: "abana, children"
      },
      {
        TAG: "TextInput",
        prompt: "Plural of 'umugabo' and its meaning:",
        answer: "abagabo, men"
      },
      {
        TAG: "TextInput",
        prompt: "Plural of 'umwami' and its meaning:",
        answer: "abami, kings"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Plural of 'umugore':",
        options: [
          "abagore",
          "abigore",
          "umugore"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Plural of 'umuhungu' and its meaning:",
        answer: "abahungu, boys"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Plural of 'umwigisha':",
        options: [
          "abigisha",
          "amwigisha",
          "umwigisha"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Plural of 'umukobwa' and its meaning:",
        answer: "abakobwa, girls"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Plural of 'umwigishwa':",
        options: [
          "abigishwa",
          "umwigishwa",
          "amwigishwa"
        ],
        correctIndex: 0
      }
    ]
  },
  {
    title: "II. Translation into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "The king has a wife.",
        answer: "umwami afise umugore"
      },
      {
        TAG: "TextInput",
        prompt: "The children are going.",
        answer: "abana bariko baragenda"
      },
      {
        TAG: "TextInput",
        prompt: "The man is a king.",
        answer: "umugabo ni umwami"
      },
      {
        TAG: "MultipleChoice",
        prompt: "The boys are working hard (much).",
        options: [
          "abahungu bariko barakora cane",
          "abahungu bariko bararya",
          "abahungu bariko bararira"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The pupils have a teacher.",
        answer: "abanyeshure bafise umwigisha"
      },
      {
        TAG: "PartialInput",
        prompt: "A woman is hoeing.",
        answer: "umugore ariko aracumba",
        hint: "ariko aracumba = is hoeing"
      },
      {
        TAG: "TextInput",
        prompt: "The child is not a boy.",
        answer: "umwana si umuhungu"
      },
      {
        TAG: "TextInput",
        prompt: "The man has a son.",
        answer: "umugabo afise umuhungu"
      },
      {
        TAG: "TextInput",
        prompt: "Teachers work hard (much).",
        answer: "abigisha barakora cane"
      },
      {
        TAG: "MultipleChoice",
        prompt: "The women have children.",
        options: [
          "abagore bafise abana",
          "abagore bafise abagabo",
          "abagore bafise abakobwa"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The pupil is a girl.",
        answer: "umunyeshure ni umukobwa"
      },
      {
        TAG: "TextInput",
        prompt: "The girl is not a teacher.",
        answer: "umukobwa si umwigisha"
      },
      {
        TAG: "TextInput",
        prompt: "Men have wives.",
        answer: "abagabo bafise abagore"
      },
      {
        TAG: "TextInput",
        prompt: "Pupils hoe.",
        answer: "abanyeshure baracumba"
      },
      {
        TAG: "TextInput",
        prompt: "The teacher is a man.",
        answer: "umwigisha ni umugabo"
      }
    ]
  }
];

let l = {
  title: "LESSON 2: Ni and Si",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
