// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Lesson7$Content(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("span", {
          children: [
            "LESSON 7: Class 3 ",
            JsxRuntime.jsx("i", {
              children: "in–, in–",
              className: "italic"
            })
          ],
          className: "font-bold"
        }),
        className: "border-b border-black pb-1 mb-6 text-center"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("b", {
            children: "Vocabulary:",
            className: "block mb-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "inka – cow"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "Imāna – God"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "imbwa – dog"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "impūzu – clothes"
                  })
                ]
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "indimiro – field"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "inzu – house, room"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "intebe – chair, stool"
                  })
                ]
              })
            ],
            className: "grid grid-cols-2 gap-x-8 pl-4"
          })
        ],
        className: "mb-6"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "13.",
            className: "min-w-[1.5rem]"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("b", {
                children: "Class 3:",
                className: "mr-1"
              }),
              JsxRuntime.jsx("span", {
                children: "The prefix for Class 3 is in- for both singular and plural. The context and agreements will usually indicate whether the word is singular or plural. Later we will note some variations of this prefix."
              })
            ]
          })
        ],
        className: "flex gap-4 mb-6 text-justify"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: "singular"
              }),
              JsxRuntime.jsx("span", {
                children: "plural"
              })
            ],
            className: "grid grid-cols-2 max-w-xs text-center mb-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: "possessive adjective prefix:",
                className: "whitespace-nowrap"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "ya-"
                  }),
                  JsxRuntime.jsx("span", {
                    children: "za-"
                  })
                ],
                className: "grid grid-cols-2 flex-grow text-center"
              })
            ],
            className: "flex gap-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "inka yanje"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "(my cow)",
                    className: "italic text-gray-600"
                  })
                ],
                className: "mt-2"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "inka zanje"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "(my cows)",
                    className: "italic text-gray-600"
                  })
                ],
                className: "mt-2"
              })
            ],
            className: "grid grid-cols-2 max-w-xs text-center ml-auto"
          })
        ],
        className: "ml-32 mb-8"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "14.",
            className: "min-w-[1.5rem]"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("b", {
                children: "Consonant change:",
                className: "mr-1"
              }),
              JsxRuntime.jsx("span", {
                children: "(Memorize this rule, it is used in many words.)",
                className: "italic text-sm"
              }),
              JsxRuntime.jsxs("ul", {
                children: [
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsxs("span", {
                        children: [
                          "n before all labials (",
                          JsxRuntime.jsx("b", {
                            children: "b, m, v, f, p"
                          }),
                          ") becomes ",
                          JsxRuntime.jsx("b", {
                            children: "m"
                          })
                        ],
                        className: "flex-1"
                      }),
                      JsxRuntime.jsx("span", {
                        children: "e.g. imbwa (in-bwa)",
                        className: "w-40 italic"
                      })
                    ],
                    className: "flex"
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsxs("span", {
                        children: [
                          JsxRuntime.jsx("b", {
                            children: "n + h"
                          }),
                          " becomes ",
                          JsxRuntime.jsx("b", {
                            children: "mp"
                          })
                        ],
                        className: "flex-1"
                      }),
                      JsxRuntime.jsx("span", {
                        children: "e.g. impūzu (in-huzu)",
                        className: "w-40 italic"
                      })
                    ],
                    className: "flex"
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsxs("span", {
                        children: [
                          JsxRuntime.jsx("b", {
                            children: "n + r"
                          }),
                          " becomes ",
                          JsxRuntime.jsx("b", {
                            children: "nd"
                          })
                        ],
                        className: "flex-1"
                      }),
                      JsxRuntime.jsx("span", {
                        children: "e.g. indimiro (in-rimiro)",
                        className: "w-40 italic"
                      })
                    ],
                    className: "flex"
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      "n before another ",
                      JsxRuntime.jsx("b", {
                        children: "n"
                      }),
                      " drops out."
                    ]
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsxs("span", {
                        children: [
                          "n before a vowel root becomes ",
                          JsxRuntime.jsx("b", {
                            children: "nz"
                          })
                        ],
                        className: "flex-1"
                      }),
                      JsxRuntime.jsx("span", {
                        children: "e.g. inzara (in-ara)",
                        className: "w-40 italic"
                      })
                    ],
                    className: "flex"
                  })
                ],
                className: "mt-4 space-y-2"
              }),
              JsxRuntime.jsxs("p", {
                children: [
                  JsxRuntime.jsx("b", {
                    children: "Note:",
                    className: "mr-1"
                  }),
                  "In the word Imana (in-mana) the n drops out before m, thus making Imana."
                ],
                className: "mt-4"
              })
            ],
            className: "flex-1"
          })
        ],
        className: "flex gap-4 text-justify"
      })
    ],
    className: "max-w-2xl mx-auto p-8 font-serif text-[11pt] leading-normal text-gray-900"
  });
}

let Content = {
  make: Lesson7$Content
};

let l_content = JsxRuntime.jsx(Lesson7$Content, {});

let l_vocabulary = [
  [
    "inka",
    "cow"
  ],
  [
    "Imana",
    "God"
  ],
  [
    "imbwa",
    "dog"
  ],
  [
    "impūzu",
    "clothes"
  ],
  [
    "indimiro",
    "field"
  ],
  [
    "inzu",
    "house, room"
  ],
  [
    "intebe",
    "chair, stool"
  ]
];

let l_examples = [
  [
    "inka yanje",
    "my cow (singular possessive)"
  ],
  [
    "inka zanje",
    "my cows (plural possessive)"
  ],
  [
    "imbwa (in-bwa)",
    "dog (n before labial → m)"
  ],
  [
    "impuzu (in-huzu)",
    "clothes (n + h → mp)"
  ],
  [
    "indimiro (in-rimiro)",
    "field (n + r → nd)"
  ],
  [
    "Imana (in-mana)",
    "God (n before m drops out)"
  ],
  [
    "inzara (in-ara)",
    "hunger (n before vowel → nz)"
  ]
];

let l_quiz = [
  {
    title: "I. Translate from Kirundi to English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Inka z’umugabo.",
        answer: "The man's cows."
      },
      {
        TAG: "TextInput",
        prompt: "Umutama n’imbwa yiwe.",
        answer: "The child and his dog."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Umuhungu akora mu ndimiro yiwe.",
        options: [
          "The boy works in his field.",
          "The girl works in her field.",
          "The boy is playing in his field.",
          "The boy works in the house."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Abakobwa bafise intebe zabo.",
        answer: "The girls have their chairs."
      },
      {
        TAG: "TextInput",
        prompt: "Umukobwa afise impuzu mu nzu yanje.",
        answer: "The girl has clothes in my house."
      },
      {
        TAG: "TextInput",
        prompt: "Umwana afise impuzu zawe.",
        answer: "The child has your clothes."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Inka zawe ziri mu murima wanje.",
        options: [
          "Your cows are in my field.",
          "My cows are in your field.",
          "The cows are in the field.",
          "Your cows are in the house."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Abantu bagenda mu nzu.",
        answer: "The people are going into the house."
      }
    ]
  },
  {
    title: "II. Translate from English to Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "The men’s houses.",
        answer: "Inzu z’abagabo."
      },
      {
        TAG: "TextInput",
        prompt: "The girl’s chair.",
        answer: "Intebe y’umukobwa."
      },
      {
        TAG: "MultipleChoice",
        prompt: "I have a dog.",
        options: [
          "Mfise imbwa.",
          "Mfise inka.",
          "Ndagira imbwa.",
          "Mfise umugabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Our chairs.",
        answer: "Intebe zacu."
      },
      {
        TAG: "TextInput",
        prompt: "Their cows.",
        answer: "Inka zabo."
      },
      {
        TAG: "TextInput",
        prompt: "My God in Kirundi is: Imana ______",
        answer: "yanje"
      },
      {
        TAG: "TextInput",
        prompt: "Your (pl.) clothes.",
        answer: "Impuzu zanyu."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The old man’s cows.",
        options: [
          "Inka z’umusaza.",
          "Inka z’umugabo.",
          "Inka z’umukobwa.",
          "Inka z’abagabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "The teachers’ children.",
        answer: "Abana b’abarimu."
      },
      {
        TAG: "TextInput",
        prompt: "The woman’s clothes.",
        answer: "Impuzu z’umugore."
      },
      {
        TAG: "MultipleChoice",
        prompt: "The children are going into the man’s field.",
        options: [
          "Abana bagenda mu murima w’umugabo.",
          "Abagore bagenda mu murima w’umugabo.",
          "Abana bagenda mu nzu y’umugabo.",
          "Abana bafise mu murima w’umugabo."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "I am working in the teacher’s field. → Nkora mu murima ______",
        answer: "w’umwarimu"
      },
      {
        TAG: "TextInput",
        prompt: "The women have bread on their heads.",
        answer: "Abagore bafise umugati mu mitwe yabo."
      }
    ]
  }
];

let l = {
  title: "LESSON 7: Class 3 in–, in–",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  Content,
  l,
}
/* l Not a pure module */
