// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Lesson3$Content(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("h1", {
          children: "Lesson 3: Possessive Adjective",
          className: "text-lg font-bold uppercase tracking-wide"
        }),
        className: "border-b border-black pb-1 mb-6 text-center"
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Vocabulary:",
            className: "font-bold mb-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("p", {
                children: "umūntu – person"
              }),
              JsxRuntime.jsx("p", {
                children: "umukozi – workman, employee"
              }),
              JsxRuntime.jsx("p", {
                children: "umutāma – old man"
              }),
              JsxRuntime.jsx("p", {
                children: "Umukiza – Savior"
              }),
              JsxRuntime.jsx("p", {
                children: "aravuga – he/she is speaking"
              }),
              JsxRuntime.jsx("p", {
                children: "ego(me) – yes, Note: ego, or just ē, is common for yes, but ‘egome’ is more emphatic"
              }),
              JsxRuntime.jsx("p", {
                children: "oya(ye) – no, Likewise, oyaye is more emphatic then oya."
              })
            ],
            className: "ml-6 space-y-1"
          }),
          JsxRuntime.jsx("p", {
            children: "Note: Observe especially the pronunciation of umuntu. It is almost as if the ‘ntu’ were blown through the nose.",
            className: "ml-6 mt-4 italic text-sm"
          })
        ],
        className: "mb-6"
      }),
      JsxRuntime.jsx("hr", {
        className: "my-6 border-transparent"
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: "5.",
                className: "font-bold mr-4"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "The possessive adjective ",
                    className: "font-bold inline"
                  }),
                  JsxRuntime.jsx("span", {
                    children: "is made up of two parts: the prefix which refers to and agrees with the object owned, and the suffix which refers to and agrees with the owner. (This agreement refers to the system of prefixes for the various classes as indicated in Par. 1)"
                  })
                ]
              })
            ],
            className: "flex items-start mb-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("p", {
                children: "umwana wa-nje – my child",
                className: "italic"
              }),
              JsxRuntime.jsxs("p", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "wa",
                    className: "font-mono bg-gray-100 px-1"
                  }),
                  " is the prefix which agrees with the first class singular. ",
                  JsxRuntime.jsx("span", {
                    children: "-nje",
                    className: "font-mono bg-gray-100 px-1"
                  }),
                  " means ‘me’. Thus wanje means ‘of me’, that is ‘my’. (Do not try to use –nje for ‘me’ in other instances.) The plural prefix is ",
                  JsxRuntime.jsx("span", {
                    children: "ba-.",
                    className: "font-mono bg-gray-100 px-1"
                  })
                ],
                className: "mt-2"
              })
            ],
            className: "ml-12 mb-4"
          }),
          JsxRuntime.jsx("p", {
            children: "In this lesson we introduce only the personal possessives (that is, the owner being a person). Other forms will be taught later.",
            className: "ml-6 mb-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "-nje - me"
              }),
              JsxRuntime.jsx("div", {
                children: "-cu - us"
              }),
              JsxRuntime.jsx("div", {
                children: "-we - you (sing.)"
              }),
              JsxRuntime.jsx("div", {
                children: "-nyu - you (pl.)"
              }),
              JsxRuntime.jsx("div", {
                children: "-iwe - him, her"
              }),
              JsxRuntime.jsx("div", {
                children: "-bo - them"
              })
            ],
            className: "ml-12 grid grid-cols-2 gap-x-8 max-w-sm mb-6"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Singular"
              }),
              JsxRuntime.jsx("div", {
                children: "Plural"
              })
            ],
            className: "ml-12 grid grid-cols-2 gap-x-8 font-semibold mb-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "wanje - my"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "wawe - your (sing.)"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "wiwe - his, hers"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "wacu - our"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "wanyu - your (pl.)"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "wabo - their"
                  })
                ],
                className: "space-y-1"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("p", {
                    children: "banje - my"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "bawe - your"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "biwe - his, hers"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "bacu - our"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "banyu - your"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "babo - their"
                  })
                ],
                className: "space-y-1"
              })
            ],
            className: "ml-12 grid grid-cols-2 gap-x-8 mb-6 border-t pt-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("p", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "Note the contraction in 3rd person singular: ",
                    className: "italic"
                  }),
                  "wa-iwe = wiwe, ba-iwe = biwe."
                ]
              }),
              JsxRuntime.jsx("p", {
                children: "e.g. umwana wiwe – his child, abana biwe – his children, abana babo – their children",
                className: "italic"
              }),
              JsxRuntime.jsx("p", {
                children: "Note: the possessive regularly follows the noun it modifies.",
                className: "font-medium underline decoration-gray-300"
              })
            ],
            className: "ml-12 space-y-3"
          })
        ],
        className: "mb-8"
      }),
      JsxRuntime.jsx("section", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("span", {
              children: "6.",
              className: "font-bold mr-4"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                  children: "Mbega.",
                  className: "font-bold inline"
                }),
                JsxRuntime.jsx("span", {
                  children: " This word introduces a question, but is not translated. It is not necessary always to use it in questions. It elides before a vowel. e.g. Mbeg’ abigishwa bararima? – Are the pupils hoeing?"
                })
              ]
            })
          ],
          className: "flex items-start"
        })
      })
    ],
    className: "max-w-2xl mx-auto p-8 font-serif text-gray-800 bg-white leading-relaxed"
  });
}

let Content = {
  make: Lesson3$Content
};

let l_content = JsxRuntime.jsx(Lesson3$Content, {});

let l_vocabulary = [
  [
    "umūntu",
    "person (nasalized 'ntu')"
  ],
  [
    "umukozi",
    "workman, employee"
  ],
  [
    "umutāma",
    "old man"
  ],
  [
    "Umukiza",
    "Savior"
  ],
  [
    "aravuga",
    "he/she is speaking"
  ],
  [
    "egome",
    "yes (emphatic)"
  ],
  [
    "oyaye",
    "no (emphatic)"
  ]
];

let l_examples = [
  [
    "umwana wanje",
    "my child"
  ],
  [
    "abana biwe",
    "his children"
  ],
  [
    "abana babo",
    "their children"
  ],
  [
    "Mbeg’ abigishwa bararima?",
    "Are the pupils hoeing?"
  ]
];

let l_quiz = [
  {
    title: "I. Translate into English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "1. Umukiza wacu ni Yesu.",
        answer: "Our Savior is Jesus"
      },
      {
        TAG: "MultipleChoice",
        prompt: "2. Umwigisha wabo aravuga.",
        options: [
          "Their teacher is speaking",
          "Our teacher is speaking",
          "Their teacher is working"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "3. Abakozi banyu bararima.",
        answer: "Your workers are hoeing"
      },
      {
        TAG: "TextInput",
        prompt: "4. Umwana wawe n’umuhungu.",
        answer: "Your child is a boy"
      },
      {
        TAG: "TextInput",
        prompt: "5. Abigishwa babo barakora.",
        answer: "Their pupils are working"
      },
      {
        TAG: "TextInput",
        prompt: "6. Abantu barakora cane.",
        answer: "The people are working hard"
      },
      {
        TAG: "MultipleChoice",
        prompt: "7. Mbeg’ umwigisha wanyu ararima?",
        options: [
          "Is my teacher hoeing?",
          "Is your teacher hoeing?",
          "Are the teachers hoeing?"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "8. Abana banje n’abakobwa.",
        answer: "My children are girls"
      }
    ]
  },
  {
    title: "II. Translate into Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "1. My child.",
        answer: "Umwana wanje"
      },
      {
        TAG: "TextInput",
        prompt: "2. Your (sing.) husband.",
        answer: "Umugabo wawe"
      },
      {
        TAG: "MultipleChoice",
        prompt: "3. His workmen.",
        options: [
          "Abakozi biwe",
          "Abakozi babo",
          "Umukozi wiwe"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "4. Your (pl.) teachers.",
        answer: "Abigisha banyu"
      },
      {
        TAG: "TextInput",
        prompt: "5. Your (sing.) children.",
        answer: "Abana bawe"
      },
      {
        TAG: "TextInput",
        prompt: "6. Her pupils.",
        answer: "Abigishwa biwe"
      },
      {
        TAG: "TextInput",
        prompt: "7. Our Savior.",
        answer: "Umukiza wacu"
      },
      {
        TAG: "TextInput",
        prompt: "8. Our boys.",
        answer: "Abahungu bacu"
      },
      {
        TAG: "MultipleChoice",
        prompt: "9. Their wives.",
        options: [
          "Abagore banje",
          "Abagore babo",
          "Abagore banyu"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "10. Your (pl.) girls.",
        answer: "Abakobwa banyu"
      },
      {
        TAG: "MultipleChoice",
        prompt: "11. The old men work (are working).",
        options: [
          "Abasaza barakora",
          "Umusage arakora",
          "Abasaza bararima"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "12. Your (pl.) king.",
        answer: "Umwami wanyu"
      },
      {
        TAG: "TextInput",
        prompt: "13. Our children are hoeing.",
        answer: "Abana bacu bararima"
      },
      {
        TAG: "TextInput",
        prompt: "14. Your (pl.) children are girls.",
        answer: "Abana banyu n'abakobwa"
      },
      {
        TAG: "TextInput",
        prompt: "15. My sons are not pupils.",
        answer: "Abahungu banje si abigishwa"
      }
    ]
  }
];

let l = {
  title: "LESSON 3: Possessive Adjectives",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  Content,
  l,
}
/* l Not a pure module */
