// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let l_content = JsxRuntime.jsxs("div", {
  children: [
    JsxRuntime.jsx("p", {
      children: "These are the primary descriptive adjectives in common use. They take the prefix of the noun (minus initial vowel) and agree in class/number with the noun they modify. They always follow the noun.",
      className: "mb-4"
    }),
    JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("table", {
        children: [
          JsxRuntime.jsx("thead", {
            children: JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("th", {
                  children: "Adjective Stem",
                  className: "border border-gray-300 px-4 py-2 text-left font-medium"
                }),
                JsxRuntime.jsx("th", {
                  children: "Meanings",
                  className: "border border-gray-300 px-4 py-2 text-left font-medium"
                }),
                JsxRuntime.jsx("th", {
                  children: "Notes",
                  className: "border border-gray-300 px-4 py-2 text-left font-medium"
                })
              ]
            }),
            className: "bg-gray-100"
          }),
          JsxRuntime.jsxs("tbody", {
            children: [
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-bi",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "bad, dirty, ugly",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-bisi",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "raw, fresh, uncooked, wet, unboiled (liquids)",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Cannot always be used for \"wet\"",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-gari",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "wide, broad",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Rarely used (e.g., for lakes)",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-gufi",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "short, low, shallow",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Sometimes gufinya or gufiya",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-īnshi",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "much, many",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-īza",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "good, clean, beautiful, nice, pretty",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-ke",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "few, scanty, little (quantity)",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Sometimes kenya or keya",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-kuru",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "important, senior, great",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-nini",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "big, thick, large, wide, broad",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Sometimes -ninīya",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-nzīnya",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "very small, tiny",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Used only with 7th class",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-rē-re",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "tall, long, high, deep",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Prefix repeated as well as stem (muremure)",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-sa",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "mere, only, alone",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-sha",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "new",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Often: -shāsha",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-to",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "small, little (size), young, thin",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Sometimes tōnya or tōya",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-tōto",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "green, unripe",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "Not ready for picking, used only of certain foods",
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ]
              }),
              JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: "-zima",
                    className: "border border-gray-300 px-4 py-2 font-mono"
                  }),
                  JsxRuntime.jsx("td", {
                    children: "alive, whole, living",
                    className: "border border-gray-300 px-4 py-2"
                  }),
                  JsxRuntime.jsx("td", {
                    className: "border border-gray-300 px-4 py-2 text-gray-600"
                  })
                ],
                className: "bg-gray-50"
              })
            ]
          })
        ],
        className: "min-w-full border border-gray-300"
      }),
      className: "overflow-x-auto"
    }),
    JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h3", {
          children: "Important Notes:",
          className: "font-bold text-lg mb-2 text-blue-800"
        }),
        JsxRuntime.jsxs("ul", {
          children: [
            JsxRuntime.jsxs("li", {
              children: [
                "Usually for \"wide\" use ",
                JsxRuntime.jsx("span", {
                  children: "-nini",
                  className: "font-mono"
                }),
                ", not ",
                JsxRuntime.jsx("span", {
                  children: "-gari",
                  className: "font-mono"
                })
              ]
            }),
            JsxRuntime.jsx("li", {
              children: "These are the ONLY descriptive adjectives in common use"
            }),
            JsxRuntime.jsx("li", {
              children: "Most other descriptive adjectives are formed from verbs/nouns"
            }),
            JsxRuntime.jsx("li", {
              children: "If both a descriptive and possessive adjective follow a noun, the possessive comes immediately after the noun"
            }),
            JsxRuntime.jsx("li", {
              children: "If an adjective refers to quantity, it usually comes last"
            })
          ],
          className: "list-disc pl-5 space-y-1 text-blue-700"
        })
      ],
      className: "mt-6 p-4 bg-blue-50 border border-blue-200 rounded"
    })
  ],
  className: "space-y-4"
});

let l_vocabulary = [
  [
    "-bi",
    "bad, dirty, ugly"
  ],
  [
    "-bisi",
    "raw, fresh, uncooked, wet, unboiled (liquids)"
  ],
  [
    "-gari",
    "wide, broad (rarely used)"
  ],
  [
    "-gufi",
    "short, low, shallow"
  ],
  [
    "-īnshi",
    "much, many"
  ],
  [
    "-īza",
    "good, clean, beautiful, nice, pretty"
  ],
  [
    "-ke",
    "few, scanty, little (quantity)"
  ],
  [
    "-kuru",
    "important, senior, great"
  ],
  [
    "-nini",
    "big, thick, large, wide, broad"
  ],
  [
    "-nzīnya",
    "very small, tiny (7th class only)"
  ],
  [
    "-rē-re",
    "tall, long, high, deep"
  ],
  [
    "-sa",
    "mere, only, alone"
  ],
  [
    "-sha",
    "new (often -shāsha)"
  ],
  [
    "-to",
    "small, little (size), young, thin"
  ],
  [
    "-tōto",
    "green, unripe (certain foods only)"
  ],
  [
    "-zima",
    "alive, whole, living"
  ]
];

let l_examples = [
  [
    "umuntu mubi",
    "a bad person"
  ],
  [
    "abantu babi",
    "bad people"
  ],
  [
    "umutima mubi",
    "a bad heart"
  ],
  [
    "imitima mibi",
    "bad hearts"
  ],
  [
    "nzu nsha (nshasha)",
    "a new house"
  ],
  [
    "inzu nsha",
    "new houses"
  ],
  [
    "inka ziwe nkeya",
    "his few cows"
  ],
  [
    "inka mbi nkeya",
    "a few bad cows"
  ]
];

let l_quiz = [
  {
    title: "I. Translate from Kirundi to English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Translate into English: Inka yanje ni mbi.",
        answer: "My cow is bad."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Translate into English: Umugabo ni mugufi.",
        options: [
          "The man is short.",
          "The man is tall.",
          "The man is bad."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Translate into English: Abantu si bake.",
        answer: "The people are not few."
      },
      {
        TAG: "PartialInput",
        prompt: "Translate into English: Abana banje si babi.",
        answer: "My children are not bad.",
        hint: "The word 'si' means 'not'."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into English: Umwigisha ni mukuru.",
        answer: "The teacher is old."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into English: Inzu y’umutama ni mbi.",
        answer: "The old man's house is bad."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Translate into English: Impuzu y’umwana ni ngufi.",
        options: [
          "The child's clothes are short.",
          "The child's clothes are dirty.",
          "The child's clothes are new."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Translate into English: Mfise umutsima mubi.",
        answer: "I have bad porridge."
      },
      {
        TAG: "PartialInput",
        prompt: "Translate into English: Abana bafise imitsima mike.",
        answer: "The children have few porridges.",
        hint: "'bafise' means 'they have', and 'imitsima' is plural for porridge."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into English: Intebe zanyu ni ngufi.",
        answer: "Your chairs are short."
      }
    ]
  },
  {
    title: "II. Translate from English to Kirundi",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: I have an ugly dog.",
        answer: "Mfise imbwa mbi."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Translate into Kirundi: Our house is low.",
        options: [
          "Inzu yacu ni ngufi.",
          "Inzu yacu ni nkuru.",
          "Inzu yacu ni mbi."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: Your (pl.) chairs are short.",
        answer: "Intebe zanyu ni ngufi."
      },
      {
        TAG: "PartialInput",
        prompt: "Translate into Kirundi: His bad children.",
        answer: "Abana be babi.",
        hint: "Use 'be' for 'his', and 'babi' for 'bad'."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: Their few cows.",
        answer: "Inka zabo nke."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: The houses are few.",
        answer: "Amazu ni make."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Translate into Kirundi: Your (sing.) clothes are dirty.",
        options: [
          "Impuzu yawe ni mbi.",
          "Impuzu yawe ni ngufi.",
          "Impuzu yawe ni nkuru."
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: God is very great.",
        answer: "Imana ni nkuru cyane."
      },
      {
        TAG: "PartialInput",
        prompt: "Translate into Kirundi: I have his short rope.",
        answer: "Mfise umugozi we mugufi.",
        hint: "'umugozi' means rope, 'we' means his, 'mugufi' means short."
      },
      {
        TAG: "TextInput",
        prompt: "Translate into Kirundi: Is the teacher’s child bad?",
        answer: "Umwana w’umwigisha ni mbi?"
      }
    ]
  }
];

let l = {
  title: "LESSON 8: Adjectives - Descriptive Adjectives",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* l Not a pure module */
