#!/bin/bash
# Start a http server with self-signed certificates on your local machine so 
# you can test out PWA features on your smartphone
npm run build
mkcert localhost 192.168.1.100 ::1
# TODO: use certificates generated by the previous command
cd dist 
npx http-server -S -C localhost+2.pem -K localhost+2-key.pem
cd -
rm localhost*.pem