// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lesson1 from "./1-10/lesson1.res.mjs";
import * as Lesson2 from "./1-10/lesson2.res.mjs";
import * as Lesson3 from "./1-10/lesson3.res.mjs";
import * as Lesson4 from "./1-10/lesson4.res.mjs";
import * as Lesson5 from "./1-10/lesson5.res.mjs";
import * as Lesson6 from "./1-10/lesson6.res.mjs";
import * as Lesson7 from "./1-10/lesson7.res.mjs";
import * as Lesson8 from "./1-10/lesson8.res.mjs";
import * as Lesson9 from "./1-10/lesson9.res.mjs";
import * as Lesson10 from "./1-10/lesson10.res.mjs";

let lessons = [
  Lesson1.l,
  Lesson2.l,
  Lesson3.l,
  Lesson4.l,
  Lesson5.l,
  Lesson6.l,
  Lesson7.l,
  Lesson8.l,
  Lesson9.l,
  Lesson10.l
];

export {
  lessons,
}
/* Lesson1 Not a pure module */
