// Generated by ReScript, PLEASE EDIT WITH CARE


let l_content = [
  "aaa",
  "bbb",
  "ccc"
];

let l_vocabulary = [
  [
    "d",
    "e"
  ],
  [
    "f",
    "g"
  ]
];

let l_examples = [[
    "h",
    "i"
  ]];

let l_quiz = [
  {
    title: "I. jjj",
    questions: [
      {
        TAG: "TextInput",
        prompt: "kk.",
        answer: "ll"
      },
      {
        TAG: "MultipleChoice",
        prompt: "mm",
        options: [
          "nnn",
          "ooo",
          "ppp"
        ],
        correctIndex: 65536
      }
    ]
  },
  {
    title: "II. qqq",
    questions: [{
        TAG: "PartialInput",
        prompt: "r",
        answer: "s",
        hint: "t"
      }]
  }
];

let l = {
  title: "LESSON X: xxx",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* No side effect */
