// Generated by ReScript, PLEASE EDIT WITH CARE


let l_content = [
  "Kirundi verbs are very important, but we begin with nouns.",
  "Nouns are grouped into classes, each with prefixes.",
  "Class 1 contains nouns referring to people.",
  "Singular prefix: umu-, Plural prefix: aba-."
];

let l_vocabulary = [
  [
    "umugabo",
    "man (husband)"
  ],
  [
    "umugore",
    "woman (wife)"
  ],
  [
    "umuhungu",
    "boy, son"
  ],
  [
    "umukobwa",
    "girl, daughter"
  ],
  [
    "abagabo",
    "men"
  ],
  [
    "abagore",
    "women"
  ],
  [
    "abahungu",
    "boys"
  ],
  [
    "abakobwa",
    "girls"
  ]
];

let l_examples = [
  [
    "arakora",
    "he/she works"
  ],
  [
    "barakora",
    "they work"
  ],
  [
    "aragenda",
    "he/she goes"
  ],
  [
    "baragenda",
    "they go"
  ],
  [
    "ararima",
    "he/she hoes"
  ],
  [
    "bararima",
    "they hoe"
  ]
];

let l_quiz = [
  {
    title: "I. Translate into English",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Umugabo arakora.",
        answer: "The man is working."
      },
      {
        TAG: "MultipleChoice",
        prompt: "Abahungu baragenda.",
        options: [
          "The boys are eating.",
          "The boys are going.",
          "The girls are going."
        ],
        correctIndex: 1
      }
    ]
  },
  {
    title: "II. Translate into Kirundi",
    questions: [{
        TAG: "PartialInput",
        prompt: "The girl works.",
        answer: "Umukobwa arakora.",
        hint: "Starts with 'Umuko…'"
      }]
  }
];

let l = {
  title: "LESSON 1: Class 1 umu–, aba–",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  l,
}
/* No side effect */
