// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lesson1 from "./lesson1.res.mjs";
import * as Lesson2 from "./lesson2.res.mjs";

let lessons = [
  Lesson1.l,
  Lesson2.l
];

export {
  lessons,
}
/* No side effect */
