// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Lesson12$Content(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {});
}

let Content = {
  make: Lesson12$Content
};

let l_content = JsxRuntime.jsx(Lesson12$Content, {});

let l_vocabulary = [];

let l_examples = [];

let l_quiz = [];

let l = {
  title: "LESSON X: xxx",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  Content,
  l,
}
/* l Not a pure module */
