// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let vowels = [
  {
    key: "a",
    description: "broad as in far"
  },
  {
    key: "e",
    description: "almost like a in hay"
  },
  {
    key: "i",
    description: "almost like ee in bee"
  },
  {
    key: "o",
    description: "almost like o in obey"
  },
  {
    key: "u",
    description: "like oo in food"
  }
];

let consonants = [
  {
    key: "b",
    description: "soft sound with lips barely touching (hard after 'm')."
  },
  {
    key: "c",
    description: "always has the sound of 'ch' as in church."
  },
  {
    key: "j",
    description: "almost like 'j' in just."
  },
  {
    key: "l",
    description: "only in foreign words (e.g., ishuli)."
  },
  {
    key: "r",
    description: "trilled; tongue flips against the roof of the mouth."
  },
  {
    key: "z",
    description: "usually has a slight 'd' sound before it."
  },
  {
    key: "bw",
    description: "always pronounced 'bg'."
  },
  {
    key: "nn",
    description: "in past stems, pronounced like 'n + ng'; otherwise 'n'."
  },
  {
    key: "rw",
    description: "pronounced as if there were a soft 'g' between r and w."
  },
  {
    key: "ry",
    description: "slight 'g' sound between r and y."
  },
  {
    key: "rty",
    description: "Must be learned from an African (unique sound)."
  },
  {
    key: "sw / sy",
    description: "slight 'k' sound between the two letters."
  }
];

let phrases = [
  {
    kirundi: [
      "Bwakeye.",
      "Bwakeye neza."
    ],
    english: "Good morning (first meeting of the day)."
  },
  {
    kirundi: [
      "Ndagize bwakeye.",
      "Ndaguhaye bwakeye."
    ],
    english: "Good morning (to a superior)."
  },
  {
    kirundi: [
      "Mwiriwe.",
      "Mwiriwe neza."
    ],
    english: "Good afternoon/evening (subsequent meetings)."
  },
  {
    kirundi: [
      "N'amaki?",
      "N'amahoro?"
    ],
    english: "What's the news? / Is it peace?"
  },
  {
    kirundi: [
      "N'amahoro.",
      "N'amarembe."
    ],
    english: "It's peace (all is well)."
  },
  {
    kirundi: [
      "N'ameza.",
      "N'amabi."
    ],
    english: "It's good news / It's bad news."
  },
  {
    kirundi: [
      "Uragumye?",
      "Urakomeye?"
    ],
    english: "Are you well?"
  },
  {
    kirundi: [
      "Ndagumye.",
      "Ndakomeye."
    ],
    english: "I'm well."
  },
  {
    kirundi: [
      "N'agasaga.",
      "N'akagaruka."
    ],
    english: "Good-bye / See you soon."
  }
];

function Lesson0$Introduction(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Introduction",
        className: "text-xl font-bold text-center mb-8 uppercase tracking-widest"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("p", {
            children: "As you begin your study of Kirundi there are several things that should be called to your attention. The first is that it will require serious study and application and a willingness to work hard. Never be content with the mediocre. There are those who talk about learning enough Kirundi to \"get by\". But you will not succeed in your relationships with Africans as long as that is your aim. And many times the one who thinks he is \"geting by\" is often misunderstood by the Africans and also he fails to understand them correctly. Aim to speak as much like Africans as possible, and never be satisfied with your achievements. There is always room for improvement. Be willing to let others show you your mistakes. Often in this way you will learn things that you might never have noticed for yourself.",
            className: "indent-12"
          }),
          JsxRuntime.jsx("p", {
            children: "Kirundi is a rich language with many words having similar meanings, yet fine shades of thought. Two words may be translated by the same English word and yet they may not be used interchangeably. So strive to find out the exact meaning of words. Also, it is important to remember that each Kirundi word does not have an exact English equivalent, and likewise, do not expect to find a Kirundi equivalent for every English word. You have heard about \"thinking black\". Africans do not think in the same terms and expressions as we do. The more you learn to think in Kirundi and express yourself as they do the more your speech will resemble theirs and the better you will be understood. Some people never get over trying to translate literally into Kirundi our English expressions.",
            className: "indent-12"
          }),
          JsxRuntime.jsxs("p", {
            children: [
              "Develop a keen ear. Listen carefully even when you do not understand what is being said. Learn your pronunciation ",
              JsxRuntime.jsx("span", {
                children: "from an African, not a European",
                className: "italic"
              }),
              ". Most Europeans have certain peculiarities of pronunciation, so it is ",
              JsxRuntime.jsx("span", {
                children: "most",
                className: "italic font-semibold"
              }),
              " important to copy the Africans’ pronunciation. It is well during the first year to spend time every day reading and talking with an African. You may know the grammar perfectly, but if your pronunciation is bad or your expressions are too \"English\" you will not be understood. Kirundi is a tonal language, which means that variations of pitch of voice, as well as length of syllables, will completely change the meaning. Not much is indicated in these lessons about tones of individual words, except in a few cases. But all vocabulary and exercises should be practiced with an African, with particular attention being given to tone. It is well to develop some system of your own of marking the tones of words."
            ],
            className: "indent-12"
          }),
          JsxRuntime.jsx("p", {
            children: "Now here are a few suggestions on pronunciation:",
            className: "indent-12 font-semibold"
          })
        ],
        className: "space-y-6 text-justify"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("section", {
            children: [
              JsxRuntime.jsxs("h2", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "A."
                  }),
                  JsxRuntime.jsx("span", {
                    children: "The Vowels:"
                  })
                ],
                className: "font-bold flex gap-4 mb-2"
              }),
              JsxRuntime.jsxs("ul", {
                children: [
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "a",
                        className: "inline-block w-8 font-mono"
                      }),
                      "is broad as in f",
                      JsxRuntime.jsx("u", {
                        children: "a",
                        className: "decoration-1"
                      }),
                      "r"
                    ]
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "e",
                        className: "inline-block w-8 font-mono"
                      }),
                      "is almost like a in hay"
                    ]
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "i",
                        className: "inline-block w-8 font-mono"
                      }),
                      "is almost like ee in bee"
                    ]
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "o",
                        className: "inline-block w-8 font-mono"
                      }),
                      "is almost like o in obey"
                    ]
                  }),
                  JsxRuntime.jsxs("li", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "u",
                        className: "inline-block w-8 font-mono"
                      }),
                      "is like oo in food"
                    ]
                  })
                ],
                className: "ml-8 space-y-1"
              }),
              JsxRuntime.jsx("p", {
                children: "(These vowels have a slightly different quality than our English vowels but you will learn that as you listen carefully.)",
                className: "ml-8 mt-2 italic text-sm text-gray-600"
              })
            ]
          }),
          JsxRuntime.jsxs("section", {
            children: [
              JsxRuntime.jsxs("h2", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "B."
                  }),
                  JsxRuntime.jsx("span", {
                    children: "The Consonants:"
                  })
                ],
                className: "font-bold flex gap-4 mb-2"
              }),
              JsxRuntime.jsx("p", {
                children: "a, f, g, h, k, m, n, p, s, t, v, w, y are pronounced practically the same as in English.",
                className: "ml-8 mb-4"
              }),
              JsxRuntime.jsx("div", {
                children: consonants.map(c => JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: c.key,
                      className: "w-12 font-mono font-bold flex-shrink-0"
                    }),
                    JsxRuntime.jsx("span", {
                      children: c.description,
                      className: "flex-grow"
                    })
                  ],
                  className: "flex flex-row"
                }, c.key)),
                className: "ml-8 grid grid-cols-1 gap-y-3"
              })
            ]
          })
        ],
        className: "mt-8 space-y-8"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("p", {
            children: "These lessons have been prepared in view to a person’s spending a day on each lesson. Some lessons may require more than a day’s study. Do not feel when you have finished them that you have \"arrived\" and need no further study. This much should be known at the end of one year. But there is a great deal that is not even touched on here. Even though you may become busy in your work, do not allow yourself to become too busy to go on with your language study. It is far more important than many other things you might do.",
            className: "indent-12"
          }),
          JsxRuntime.jsx("p", {
            children: "Kirundi varies from one locality to another. Certain words and forms are much more common in some areas than in others, or may have a different meaning than elsewhere. Find what is best where you are and learn that. But beware of saying that a word is not used until you have investigated carefully.",
            className: "indent-12"
          })
        ],
        className: "mt-12 space-y-6 text-justify"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h3", {
            children: "Expressions you’ll want to know first:",
            className: "text-lg font-bold mb-4"
          }),
          JsxRuntime.jsx("table", {
            children: JsxRuntime.jsx("tbody", {
              children: phrases.map((p, i) => JsxRuntime.jsxs("tr", {
                children: [
                  JsxRuntime.jsx("td", {
                    children: p.kirundi.map(line => JsxRuntime.jsx("div", {
                      children: line
                    }, line)),
                    className: "py-4 pr-4 align-top w-1/3 font-semibold text-blue-900"
                  }),
                  JsxRuntime.jsx("td", {
                    children: p.english,
                    className: "py-4 align-top text-gray-600"
                  })
                ],
                className: "border-b border-gray-100 last:border-0"
              }, i.toString()))
            }),
            className: "w-full border-collapse"
          })
        ],
        className: "mt-12 border-t border-gray-200 pt-8"
      })
    ],
    className: "max-w-4xl mx-auto p-8 bg-white text-gray-800 leading-relaxed font-serif"
  });
}

let Introduction = {
  vowels: vowels,
  consonants: consonants,
  phrases: phrases,
  make: Lesson0$Introduction
};

let l_content = JsxRuntime.jsx(Lesson0$Introduction, {});

let l_vocabulary = [];

let l_examples = [
  [
    "Bwakeye",
    "Good morning"
  ],
  [
    "Bwakeye neza",
    "Good morning"
  ],
  [
    "Ndagize bwakeye",
    "Good morning (to a superior)"
  ],
  [
    "Ndaguhaye bwakeye",
    "Good morning (to a superior)"
  ],
  [
    "Mwiriwe",
    "Good afternoon/evening"
  ],
  [
    "Mwiriwe neza",
    "Good afternoon/evening"
  ],
  [
    "N'amaki",
    "What's the news?"
  ],
  [
    "N'amahoro",
    "Is it peace?"
  ],
  [
    "N'amahoro",
    "It's peace"
  ],
  [
    "N'amarembe",
    "It's peace"
  ],
  [
    "N'ameza",
    "It's good news"
  ],
  [
    "N'amabi",
    "It's bad news"
  ],
  [
    "Uragumye",
    "Are you well?"
  ],
  [
    "Urakomeye",
    "Are you well?"
  ],
  [
    "Ndagumye",
    "I'm well"
  ],
  [
    "Ndakomeye",
    "I'm well"
  ],
  [
    "N'agasaga",
    "Good-bye"
  ],
  [
    "N'akagaruka",
    "Good-bye (see you soon)"
  ]
];

let l_quiz = [
  {
    title: "I. Basic Greetings",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Translate 'Good morning (first meeting)' to Kirundi:",
        answer: "Bwakeye"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Which phrase means 'Good afternoon/evening'?",
        options: [
          "Bwakeye neza",
          "Mwiriwe neza",
          "Ndagize bwakeye"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "What does 'Ndagize bwakeye' mean in English?",
        answer: "Good morning (to a superior)"
      },
      {
        TAG: "TextInput",
        prompt: "Give the formal morning greeting for superiors:",
        answer: "Ndagize bwakeye"
      }
    ]
  },
  {
    title: "II. Daily Inquiries",
    questions: [
      {
        TAG: "MultipleChoice",
        prompt: "What would you say to ask 'What's the news?'",
        options: [
          "N'amahoro",
          "N'amaki",
          "Ndagumye"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "When someone says 'N'amahoro?', they're asking:",
        answer: "Is it peace?"
      },
      {
        TAG: "TextInput",
        prompt: "How do you respond 'It's peace (all is well)' in Kirundi?",
        answer: "N'amahoro"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Which phrase indicates good news?",
        options: [
          "N'amabi",
          "N'ameza",
          "N'akagaruka"
        ],
        correctIndex: 1
      }
    ]
  },
  {
    title: "III. Health & Well-being",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Translate 'Are you well?' to Kirundi:",
        answer: "Uragumye"
      },
      {
        TAG: "MultipleChoice",
        prompt: "How do you respond 'I'm well'?",
        options: [
          "Ndagumye",
          "N'amahoro",
          "N'agasaga"
        ],
        correctIndex: 0
      },
      {
        TAG: "TextInput",
        prompt: "What is the alternative way to ask 'Urakomeye?' in English?",
        answer: "Are you well?"
      },
      {
        TAG: "TextInput",
        prompt: "Give another Kirundi phrase for 'I'm well' (besides Ndagumye):",
        answer: "Ndakomeye"
      }
    ]
  },
  {
    title: "IV. Mixed Phrases",
    questions: [
      {
        TAG: "MultipleChoice",
        prompt: "Which phrase means 'Good-bye / See you soon'?",
        options: [
          "Bwakeye neza",
          "N'agasaga",
          "N'amarembe"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "What does 'N'amarembe' mean?",
        answer: "It's peace (all is well)"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Select the evening greeting (for subsequent meetings):",
        options: [
          "Bwakeye",
          "Mwiriwe",
          "Ndaguhaye bwakeye"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "Give the alternative Kirundi phrase for 'Good-bye' besides 'N'agasaga':",
        answer: "N'akagaruka"
      }
    ]
  },
  {
    title: "V. Comprehensive Review",
    questions: [
      {
        TAG: "TextInput",
        prompt: "Translate 'Mwiriwe neza' to English:",
        answer: "Good afternoon/evening"
      },
      {
        TAG: "MultipleChoice",
        prompt: "Which is the proper response to 'N'amaki?' if everything is fine?",
        options: [
          "N'amabi",
          "N'amahoro",
          "Uragumye"
        ],
        correctIndex: 1
      },
      {
        TAG: "TextInput",
        prompt: "How would you say 'It's bad news' in Kirundi?",
        answer: "N'amabi"
      },
      {
        TAG: "TextInput",
        prompt: "What is the English meaning of 'Ndaguhaye bwakeye'?",
        answer: "Good morning (to a superior)"
      }
    ]
  }
];

let l = {
  title: "Introduction",
  content: l_content,
  vocabulary: l_vocabulary,
  examples: l_examples,
  quiz: l_quiz
};

export {
  Introduction,
  l,
}
/* l Not a pure module */
