// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lesson from "./Lesson.res.mjs";
import * as Lesson1 from "./lessons/lesson1.res.mjs";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

function App(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Lesson.LessonView.make, {
      lesson: Lesson1.lesson1
    }),
    className: "max-w-200"
  });
}

let make = App;

export {
  make,
}
/*  Not a pure module */
