// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lesson from "./Lesson.res.mjs";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as MainMenu from "./MainMenu.res.mjs";
import * as Settings from "./Settings.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Flashcards from "./Flashcards.res.mjs";
import * as LessonData from "./data/LessonData.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Dom_storage from "@rescript/runtime/lib/es6/Dom_storage.js";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

let rescript = RescriptLogoSvg;

let vite = ViteSvg;

function getCompletedVocab(lessons, maxIdx) {
  return lessons.slice(0, maxIdx + 1 | 0).flatMap(l => l.vocabulary);
}

function App(props) {
  let localStorageKey = "current-lesson-index";
  let match = React.useState(() => "MainMenu");
  let setCurrentScreen = match[1];
  let match$1 = React.useState(() => {
    let value = Dom_storage.getItem(localStorageKey, localStorage);
    if (value !== undefined) {
      return Belt_Option.getWithDefault(Belt_Int.fromString(value), 0);
    } else {
      return 0;
    }
  });
  let setSelectedIdx = match$1[1];
  let selectedIdx = match$1[0];
  let totalLessons = LessonData.lessons.length;
  React.useEffect(() => {
    Dom_storage.setItem(localStorageKey, selectedIdx.toString(), localStorage);
  }, [selectedIdx]);
  let goToNext = () => setSelectedIdx(prev => Math.min(prev + 1 | 0, totalLessons - 1 | 0));
  let goToPrev = () => setSelectedIdx(prev => Math.max(prev - 1 | 0, 0));
  let goToLessonId = id => {
    let id$1 = Stdlib_Int.clamp(0, totalLessons - 1 | 0, id);
    setSelectedIdx(param => id$1);
    setCurrentScreen(param => "LessonView");
  };
  let handleReset = param => {
    let confirm = window.confirm("Are you sure you want to reset all progress? This cannot be undone.");
    if (confirm) {
      Dom_storage.removeItem(localStorageKey, localStorage);
      setSelectedIdx(param => 0);
      return setCurrentScreen(param => "MainMenu");
    }
  };
  let handleChange = event => {
    let value = event.target.value;
    setSelectedIdx(param => Belt_Option.getWithDefault(Belt_Int.fromString(value), 0));
  };
  switch (match[0]) {
    case "MainMenu" :
      return JsxRuntime.jsx(MainMenu.make, {
        onStart: () => setCurrentScreen(param => "LessonView"),
        onLessonSelect: goToLessonId,
        onSettings: () => setCurrentScreen(param => "Settings"),
        lastLessonId: selectedIdx,
        onFlashcards: () => setCurrentScreen(param => "Flashcards")
      });
    case "LessonView" :
      let lesson = Belt_Array.get(LessonData.lessons, selectedIdx);
      if (lesson !== undefined) {
        return JsxRuntime.jsx(Lesson.Container.make, {
          lesson: lesson,
          selectedIdx: selectedIdx,
          totalLessons: totalLessons,
          onBack: () => setCurrentScreen(param => "MainMenu"),
          onSettings: () => setCurrentScreen(param => "Settings"),
          onNext: goToNext,
          onPrev: goToPrev,
          onSelectChange: handleChange
        });
      } else {
        return "Lesson not found";
      }
    case "Settings" :
      return JsxRuntime.jsx(Settings.make, {
        onBack: () => setCurrentScreen(param => "MainMenu"),
        onReset: handleReset
      });
    case "Flashcards" :
      return JsxRuntime.jsx(Flashcards.make, {
        vocabulary: getCompletedVocab(LessonData.lessons, selectedIdx),
        onBack: param => setCurrentScreen(param => "MainMenu")
      });
  }
}

let make = App;

export {
  rescript,
  vite,
  getCompletedVocab,
  make,
}
/* rescript Not a pure module */
