// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SRS from "./SRS.res.mjs";
import * as React from "react";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Dom_storage from "@rescript/runtime/lib/es6/Dom_storage.js";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as JsxRuntime from "react/jsx-runtime";

function Flashcards$SRSButton(props) {
  return JsxRuntime.jsx("button", {
    children: props.label,
    className: props.color + ` text-white py-4 px-2 rounded-xl font-bold text-xs uppercase shadow-lg active:scale-95 transition-transform`,
    onClick: props.onClick
  });
}

function serializeStats(map) {
  return Belt_Option.getWithDefault(JSON.stringify(Belt_MapString.toArray(map)), "{}");
}

function Flashcards(props) {
  let onBack = props.onBack;
  let vocabulary = props.vocabulary;
  let localStorageKey = "srs-stats-v1";
  let match = React.useState(() => {
    let json = Dom_storage.getItem(localStorageKey, localStorage);
    if (json !== undefined) {
      try {
        return Belt_MapString.fromArray(JSON.parse(json));
      } catch (exn) {
        return;
      }
    }
  });
  let setStatsMap = match[1];
  let statsMap = match[0];
  let match$1 = React.useState(() => {
    let now = Date.now();
    return vocabulary.filter(param => {
      let stats = Belt_MapString.getWithDefault(statsMap, param[0], SRS.defaultStats);
      let dueTime = stats.lastReviewed + stats.interval * 86400000.0;
      return now >= dueTime;
    }).map(param => ({
      kirundi: param[0],
      english: param[1],
      isReversed: Math.random() > 0.5,
      isDue: true
    }));
  });
  let deck = match$1[0];
  let match$2 = React.useState(() => 0);
  let setCurrentIndex = match$2[1];
  let currentIndex = match$2[0];
  let match$3 = React.useState(() => false);
  let setIsFlipped = match$3[1];
  let isFlipped = match$3[0];
  let currentCard = deck[currentIndex];
  let totalCards = deck.length;
  let handleFlip = param => setIsFlipped(prev => !prev);
  let handleReview = result => {
    if (currentCard === undefined) {
      return;
    }
    let currentStats = Belt_MapString.getWithDefault(statsMap, currentCard.kirundi, SRS.defaultStats);
    let newStats = SRS.calculateNextReview(currentStats, result);
    let newMap = Belt_MapString.set(statsMap, currentCard.kirundi, newStats);
    setStatsMap(param => newMap);
    Dom_storage.setItem(localStorageKey, serializeStats(newMap), localStorage);
    setIsFlipped(param => false);
    setTimeout(() => setCurrentIndex(prev => prev + 1 | 0), 200);
  };
  let tmp;
  if (currentCard !== undefined) {
    let frontText = currentCard.isReversed ? currentCard.english : currentCard.kirundi;
    let frontLabel = currentCard.isReversed ? "English" : "Kirundi";
    let backText = currentCard.isReversed ? currentCard.kirundi : currentCard.english;
    let backLabel = currentCard.isReversed ? "Kirundi" : "English";
    tmp = JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: frontLabel,
                className: "text-sm text-indigo-400 font-bold uppercase tracking-widest mb-4"
              }),
              JsxRuntime.jsx("h2", {
                children: frontText,
                className: "text-3xl font-bold text-gray-800"
              }),
              JsxRuntime.jsx("p", {
                children: "Tap to flip",
                className: "mt-8 text-gray-400 text-sm italic"
              })
            ],
            className: "absolute inset-0 backface-hidden bg-white rounded-3xl shadow-xl border-2 border-indigo-100 flex flex-col items-center justify-center p-8 text-center"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: backLabel,
                className: "text-sm text-indigo-200 font-bold uppercase tracking-widest mb-4"
              }),
              JsxRuntime.jsx("h2", {
                children: backText,
                className: "text-3xl font-bold text-white"
              })
            ],
            className: "absolute inset-0 backface-hidden bg-indigo-600 rounded-3xl shadow-xl flex flex-col items-center justify-center p-8 text-center rotate-y-180"
          })
        ],
        className: `relative w-full h-full duration-500 preserve-3d transition-all ` + (
          isFlipped ? "rotate-y-180" : ""
        )
      }),
      className: "relative w-full max-w-sm aspect-[3/4] cursor-pointer group perspective",
      onClick: handleFlip
    });
  } else {
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h2", {
          children: "All caught up!",
          className: "text-2xl font-bold mb-4"
        }),
        JsxRuntime.jsx("button", {
          children: "Return to Menu",
          className: "bg-indigo-600 text-white px-6 py-2 rounded-lg",
          onClick: onBack
        })
      ],
      className: "text-center"
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("button", {
            children: [
              JsxRuntime.jsx("svg", {
                children: JsxRuntime.jsx("path", {
                  d: "M15 19l-7-7 7-7",
                  strokeLinecap: "round",
                  strokeLinejoin: "round",
                  strokeWidth: "2"
                }),
                className: "w-5 h-5",
                fill: "none",
                stroke: "currentColor",
                viewBox: "0 0 24 24"
              }),
              "Back"
            ],
            className: "text-gray-600 font-medium flex items-center gap-2",
            onClick: onBack
          }),
          JsxRuntime.jsx("div", {
            children: `Card ` + (currentIndex + 1 | 0).toString() + ` of ` + totalCards.toString(),
            className: "text-sm font-semibold text-gray-500"
          })
        ],
        className: "flex items-center justify-between mb-8"
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "flex-grow flex items-center justify-center"
      }),
      isFlipped ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx(Flashcards$SRSButton, {
              label: "Again",
              color: "bg-red-500",
              onClick: param => handleReview("Again")
            }),
            JsxRuntime.jsx(Flashcards$SRSButton, {
              label: "Hard",
              color: "bg-orange-500",
              onClick: param => handleReview("Hard")
            }),
            JsxRuntime.jsx(Flashcards$SRSButton, {
              label: "Good",
              color: "bg-green-500",
              onClick: param => handleReview("Good")
            }),
            JsxRuntime.jsx(Flashcards$SRSButton, {
              label: "Easy",
              color: "bg-blue-500",
              onClick: param => handleReview("Easy")
            })
          ],
          className: "mt-8 grid grid-cols-4 gap-2 max-w-md mx-auto w-full pb-10"
        }) : JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("p", {
            children: "Tap card to see answer",
            className: "text-gray-400 animate-bounce"
          }),
          className: "mt-8 flex justify-center pb-10"
        })
    ],
    className: "flex flex-col min-h-screen bg-gray-50 p-6"
  });
}

let make = Flashcards;

export {
  make,
}
/* react Not a pure module */
