// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Flashcards(props) {
  let vocabulary = props.vocabulary;
  let match = React.useState(() => {
    let newDeck = vocabulary.map(param => ({
      kirundi: param[0],
      english: param[1],
      isReversed: Math.random() > 0.5
    }));
    Stdlib_Array.shuffle(newDeck);
    return newDeck;
  });
  let deck = match[0];
  let match$1 = React.useState(() => 0);
  let setCurrentIndex = match$1[1];
  let currentIndex = match$1[0];
  let match$2 = React.useState(() => false);
  let setIsFlipped = match$2[1];
  let currentCard = deck[currentIndex];
  let totalCards = deck.length;
  let handleNext = () => {
    setIsFlipped(param => false);
    setCurrentIndex(prev => Math.min(prev + 1 | 0, totalCards - 1 | 0));
  };
  let handlePrev = () => {
    setIsFlipped(param => false);
    setCurrentIndex(prev => Math.max(prev - 1 | 0, 0));
  };
  let handleFlip = param => setIsFlipped(prev => !prev);
  let tmp;
  if (currentCard !== undefined) {
    let frontText = currentCard.isReversed ? currentCard.english : currentCard.kirundi;
    let frontLabel = currentCard.isReversed ? "English" : "Kirundi";
    let backText = currentCard.isReversed ? currentCard.kirundi : currentCard.english;
    let backLabel = currentCard.isReversed ? "Kirundi" : "English";
    tmp = JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: frontLabel,
                className: "text-sm text-indigo-400 font-bold uppercase tracking-widest mb-4"
              }),
              JsxRuntime.jsx("h2", {
                children: frontText,
                className: "text-3xl font-bold text-gray-800"
              }),
              JsxRuntime.jsx("p", {
                children: "Tap to flip",
                className: "mt-8 text-gray-400 text-sm italic"
              })
            ],
            className: "absolute inset-0 backface-hidden bg-white rounded-3xl shadow-xl border-2 border-indigo-100 flex flex-col items-center justify-center p-8 text-center"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: backLabel,
                className: "text-sm text-indigo-200 font-bold uppercase tracking-widest mb-4"
              }),
              JsxRuntime.jsx("h2", {
                children: backText,
                className: "text-3xl font-bold text-white"
              })
            ],
            className: "absolute inset-0 backface-hidden bg-indigo-600 rounded-3xl shadow-xl flex flex-col items-center justify-center p-8 text-center rotate-y-180"
          })
        ],
        className: `relative w-full h-full duration-500 preserve-3d transition-all ` + (
          match$2[0] ? "rotate-y-180" : ""
        )
      }),
      className: "relative w-full max-w-sm aspect-[3/4] cursor-pointer group perspective",
      onClick: handleFlip
    });
  } else {
    tmp = "No cards available.";
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("button", {
            children: [
              JsxRuntime.jsx("svg", {
                children: JsxRuntime.jsx("path", {
                  d: "M15 19l-7-7 7-7",
                  strokeLinecap: "round",
                  strokeLinejoin: "round",
                  strokeWidth: "2"
                }),
                className: "w-5 h-5",
                fill: "none",
                stroke: "currentColor",
                viewBox: "0 0 24 24"
              }),
              "Back"
            ],
            className: "text-gray-600 font-medium flex items-center gap-2",
            onClick: props.onBack
          }),
          JsxRuntime.jsx("div", {
            children: `Card ` + (currentIndex + 1 | 0).toString() + ` of ` + totalCards.toString(),
            className: "text-sm font-semibold text-gray-500"
          })
        ],
        className: "flex items-center justify-between mb-8"
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "flex-grow flex items-center justify-center"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                d: "M15 19l-7-7 7-7",
                strokeLinecap: "round",
                strokeLinejoin: "round",
                strokeWidth: "2"
              }),
              className: "w-6 h-6",
              fill: "none",
              stroke: "currentColor",
              viewBox: "0 0 24 24"
            }),
            className: "p-4 rounded-full bg-white shadow-md text-gray-600 disabled:opacity-30",
            disabled: currentIndex === 0,
            onClick: param => handlePrev()
          }),
          JsxRuntime.jsx("button", {
            children: JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                d: "M9 5l7 7-7 7",
                strokeLinecap: "round",
                strokeLinejoin: "round",
                strokeWidth: "2"
              }),
              className: "w-6 h-6",
              fill: "none",
              stroke: "currentColor",
              viewBox: "0 0 24 24"
            }),
            className: "p-4 rounded-full bg-indigo-600 shadow-lg text-white disabled:opacity-30",
            disabled: currentIndex === (totalCards - 1 | 0),
            onClick: param => handleNext()
          })
        ],
        className: "mt-12 flex justify-center items-center gap-8 pb-10"
      })
    ],
    className: "flex flex-col min-h-screen bg-gray-50 p-6"
  });
}

let make = Flashcards;

export {
  make,
}
/* react Not a pure module */
