// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Quiz from "./Quiz.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Lesson$Vocabulary(props) {
  return JsxRuntime.jsx("ul", {
    children: props.items.map(param => {
      let k = param[0];
      return JsxRuntime.jsx("li", {
        children: k + " – " + param[1],
        className: "text-sm"
      }, k);
    }),
    className: "list-disc pl-6 space-y-1 text-gray-700"
  });
}

let Vocabulary = {
  make: Lesson$Vocabulary
};

function Lesson$LessonView(props) {
  let lesson = props.lesson;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: lesson.title,
        className: "text-3xl font-extrabold tracking-tight text-gray-900"
      }),
      JsxRuntime.jsx("div", {
        children: lesson.content,
        className: "space-y-4 text-gray-700"
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Quiz",
            className: "text-xl font-semibold text-gray-900"
          }),
          lesson.quiz.map(s => JsxRuntime.jsx(Quiz.make, {
            section: s
          }, s.title))
        ],
        className: "space-y-6"
      })
    ],
    className: "mx-auto max-w-3xl space-y-8 px-4 py-8"
  });
}

let LessonView = {
  make: Lesson$LessonView
};

export {
  Vocabulary,
  LessonView,
}
/* Quiz Not a pure module */
