// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Quiz from "./Quiz.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as LessonData from "./data/LessonData.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Lesson$Vocabulary(props) {
  return JsxRuntime.jsx("ul", {
    children: props.items.map(param => {
      let k = param[0];
      return JsxRuntime.jsx("li", {
        children: k + " – " + param[1],
        className: "text-sm"
      }, k);
    }),
    className: "list-disc pl-6 space-y-1 text-gray-700"
  });
}

let Vocabulary = {
  make: Lesson$Vocabulary
};

function Lesson$LessonView(props) {
  let lesson = props.lesson;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: lesson.title,
        className: "text-3xl font-extrabold tracking-tight text-gray-900"
      }),
      JsxRuntime.jsx("div", {
        children: lesson.content,
        className: "space-y-4 text-gray-700"
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Quiz",
            className: "text-xl font-semibold text-gray-900"
          }),
          lesson.quiz.map(s => JsxRuntime.jsx(Quiz.make, {
            section: s
          }, s.title))
        ],
        className: "space-y-6"
      })
    ],
    className: "mx-auto max-w-3xl space-y-8 px-4 py-8"
  });
}

let LessonView = {
  make: Lesson$LessonView
};

function Lesson$Container(props) {
  let onPrev = props.onPrev;
  let onNext = props.onNext;
  let onSettings = props.onSettings;
  let onBack = props.onBack;
  let totalLessons = props.totalLessons;
  let selectedIdx = props.selectedIdx;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "← Back to Menu",
            className: "text-gray-500 hover:text-gray-800 flex items-center text-sm font-medium",
            onClick: param => onBack()
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("select", {
                children: Belt_Array.mapWithIndex(LessonData.lessons, (index, lesson) => JsxRuntime.jsx("option", {
                  children: lesson.title,
                  value: index.toString()
                }, index.toString())),
                className: "p-2 border border-gray-300 rounded-md bg-white text-sm",
                value: selectedIdx.toString(),
                onChange: props.onSelectChange
              }),
              JsxRuntime.jsx("button", {
                children: JsxRuntime.jsxs("svg", {
                  children: [
                    JsxRuntime.jsx("path", {
                      d: "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z",
                      strokeLinecap: "round",
                      strokeLinejoin: "round",
                      strokeWidth: "2"
                    }),
                    JsxRuntime.jsx("path", {
                      d: "M15 12a3 3 0 11-6 0 3 3 0 016 0z",
                      strokeLinecap: "round",
                      strokeLinejoin: "round",
                      strokeWidth: "2"
                    })
                  ],
                  className: "w-5 h-5",
                  fill: "none",
                  stroke: "currentColor",
                  viewBox: "0 0 24 24"
                }),
                className: "p-2 text-gray-400 hover:text-gray-600",
                title: "Settings",
                onClick: param => onSettings()
              })
            ],
            className: "flex items-center gap-4"
          })
        ],
        className: "flex justify-between items-center mb-8"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(Lesson$LessonView, {
          lesson: props.lesson
        }),
        className: "flex-grow"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "← Previous",
            className: "px-6 py-2 bg-gray-100 text-gray-700 rounded-lg font-semibold disabled:opacity-30 hover:bg-gray-200 transition-all",
            disabled: selectedIdx === 0,
            onClick: param => onPrev()
          }),
          JsxRuntime.jsx("span", {
            children: `Lesson ` + (selectedIdx + 1 | 0).toString() + ` of ` + totalLessons.toString(),
            className: "text-sm font-medium text-gray-500"
          }),
          JsxRuntime.jsx("button", {
            children: "Next →",
            className: "px-6 py-2 bg-indigo-600 text-white rounded-lg font-semibold disabled:bg-gray-300 hover:bg-indigo-700 shadow-sm transition-all",
            disabled: selectedIdx === (totalLessons - 1 | 0),
            onClick: param => onNext()
          })
        ],
        className: "mt-12 flex justify-between items-center border-t pt-6 pb-12"
      })
    ],
    className: "flex flex-col min-h-screen p-6 max-w-4xl mx-auto font-sans"
  });
}

let Container = {
  make: Lesson$Container
};

export {
  Vocabulary,
  LessonView,
  Container,
}
/* Quiz Not a pure module */
