// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function Lesson$Vocabulary(props) {
  return JsxRuntime.jsx("ul", {
    children: props.items.map(param => {
      let k = param[0];
      return JsxRuntime.jsx("li", {
        children: k + " – " + param[1]
      }, k);
    })
  });
}

let Vocabulary = {
  make: Lesson$Vocabulary
};

function Lesson$QuizQuestionView(props) {
  let question = props.question;
  let match = React.useState(() => "");
  let setUserInput = match[1];
  let userInput = match[0];
  let match$1 = React.useState(() => -1);
  let setSelected = match$1[1];
  let selected = match$1[0];
  let match$2 = React.useState(() => false);
  let setChecked = match$2[1];
  let checked = match$2[0];
  switch (question.TAG) {
    case "TextInput" :
      let answer = question.answer;
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("p", {
            children: question.prompt
          }),
          JsxRuntime.jsx("input", {
            value: userInput,
            onChange: e => setUserInput(param => e.target.value)
          }),
          JsxRuntime.jsx("button", {
            children: "Check",
            onClick: param => setChecked(prev => true)
          }),
          checked ? JsxRuntime.jsx("p", {
              children: userInput === answer ? "✓ Correct" : "✗ Correct answer: " + answer
            }) : null
        ]
      });
    case "MultipleChoice" :
      let correctIndex = question.correctIndex;
      let options = question.options;
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("p", {
            children: question.prompt
          }),
          JsxRuntime.jsx("ul", {
            children: options.map((opt, i) => JsxRuntime.jsx("li", {
              children: JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    checked: selected === i,
                    type: "radio",
                    onChange: param => setSelected(param => i)
                  }),
                  opt
                ]
              })
            }, i.toString()))
          }),
          JsxRuntime.jsx("button", {
            children: "Check",
            onClick: param => setChecked(prev => true)
          }),
          checked ? JsxRuntime.jsx("p", {
              children: selected === correctIndex ? "✓ Correct" : "✗ Correct answer: " + Stdlib_Option.getOr(options[correctIndex], "error: missing index")
            }) : null
        ]
      });
    case "PartialInput" :
      let answer$1 = question.answer;
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("p", {
            children: question.prompt
          }),
          JsxRuntime.jsx("input", {
            placeholder: question.hint,
            value: userInput,
            onChange: e => setUserInput(param => e.target.value)
          }),
          JsxRuntime.jsx("button", {
            children: "Check",
            onClick: param => setChecked(prev => true)
          }),
          checked ? JsxRuntime.jsx("p", {
              children: Js_string.includes(answer$1, userInput) ? "✓ On the right track" : "✗ Full answer: " + answer$1
            }) : null
        ]
      });
  }
}

let QuizQuestionView = {
  make: Lesson$QuizQuestionView
};

function Lesson$QuizSection(props) {
  let section = props.section;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h3", {
        children: section.title
      }),
      JsxRuntime.jsx("ol", {
        children: section.questions.map((q, i) => JsxRuntime.jsx("li", {
          children: JsxRuntime.jsx(Lesson$QuizQuestionView, {
            question: q
          })
        }, i.toString()))
      })
    ],
    style: {
      marginBottom: "2rem"
    }
  });
}

let QuizSection = {
  make: Lesson$QuizSection
};

function Lesson$LessonView(props) {
  let lesson = props.lesson;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: lesson.title,
        className: `font-extrabold`
      }),
      lesson.content.map(p => JsxRuntime.jsx("p", {
        children: p
      }, p)),
      JsxRuntime.jsx("h2", {
        children: "Vocabulary"
      }),
      JsxRuntime.jsx(Lesson$Vocabulary, {
        items: lesson.vocabulary
      }),
      JsxRuntime.jsx("h2", {
        children: "Verbs"
      }),
      JsxRuntime.jsx(Lesson$Vocabulary, {
        items: lesson.verbs
      }),
      JsxRuntime.jsx("h2", {
        children: "Quiz"
      }),
      lesson.quiz.map(s => JsxRuntime.jsx(Lesson$QuizSection, {
        section: s
      }, s.title))
    ]
  });
}

let LessonView = {
  make: Lesson$LessonView
};

export {
  Vocabulary,
  QuizQuestionView,
  QuizSection,
  LessonView,
}
/* react Not a pure module */
