// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MainMenu(props) {
  let onSettings = props.onSettings;
  let onStart = props.onStart;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("button", {
            children: JsxRuntime.jsxs("svg", {
              children: [
                JsxRuntime.jsx("path", {
                  d: "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z",
                  strokeLinecap: "round",
                  strokeLinejoin: "round",
                  strokeWidth: "2"
                }),
                JsxRuntime.jsx("path", {
                  d: "M15 12a3 3 0 11-6 0 3 3 0 016 0z",
                  strokeLinecap: "round",
                  strokeLinejoin: "round",
                  strokeWidth: "2"
                })
              ],
              className: "w-5 h-5",
              fill: "none",
              stroke: "currentColor",
              viewBox: "0 0 24 24"
            }),
            className: "p-2 text-gray-400 hover:text-gray-600 flex-shrink-0",
            title: "Settings",
            onClick: param => onSettings()
          }),
          className: "flex items-center gap-2 sm:gap-4 min-w-0"
        }),
        className: "sticky top-0 z-10 bg-white flex justify-between items-center py-4 px-4 sm:px-6 border-b border-gray-100 gap-2"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h1", {
                children: "Learn Kirundi",
                className: "text-4xl font-bold text-gray-900 mb-2"
              }),
              JsxRuntime.jsx("p", {
                children: "based off work from Elizabeth E. Cox.",
                className: "text-gray-600"
              })
            ],
            className: "text-center mb-8"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsxs("button", {
              children: [
                props.isStarted ? "Continue Lesson" : "Start Learning",
                JsxRuntime.jsx("span", {
                  children: "→",
                  className: "ml-2 group-hover:translate-x-1 transition-transform"
                })
              ],
              className: "group relative flex items-center justify-center px-8 py-4 bg-indigo-600 text-white text-xl font-bold rounded-2xl shadow-lg hover:bg-indigo-700 hover:-translate-y-1 transition-all",
              onClick: param => onStart()
            }),
            className: "flex flex-col gap-4 w-full max-w-xs"
          })
        ],
        className: "flex flex-col items-center justify-center flex-grow bg-gray-50 px-4"
      })
    ],
    className: "flex flex-col min-h-screen max-w-4xl mx-auto font-sans"
  });
}

let make = MainMenu;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
