// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MainMenu(props) {
  let onSettings = props.onSettings;
  let onStart = props.onStart;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "Learn Kirundi",
            className: "text-4xl font-bold text-gray-900 mb-2"
          }),
          JsxRuntime.jsx("p", {
            children: "based off work from Elizabeth E. Cox.",
            className: "text-gray-600"
          })
        ],
        className: "text-center mb-8"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("button", {
            children: [
              props.isStarted ? "Continue Lesson" : "Start Learning",
              JsxRuntime.jsx("span", {
                children: "→",
                className: "ml-2 group-hover:translate-x-1 transition-transform"
              })
            ],
            className: "group relative flex items-center justify-center px-8 py-4 bg-indigo-600 text-white text-xl font-bold rounded-2xl shadow-lg hover:bg-indigo-700 hover:-translate-y-1 transition-all",
            onClick: param => onStart()
          }),
          JsxRuntime.jsx("button", {
            children: "Settings",
            className: "text-gray-500 hover:text-indigo-600 font-medium transition-colors",
            onClick: param => onSettings()
          })
        ],
        className: "flex flex-col gap-4 w-full max-w-xs"
      })
    ],
    className: "flex flex-col items-center justify-center min-h-screen bg-gray-50 px-4"
  });
}

let make = MainMenu;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
