// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function MainMenu(props) {
  let onSettings = props.onSettings;
  let onLessonSelect = props.onLessonSelect;
  let onStart = props.onStart;
  React.useState(() => {});
  let lessonGroups = [
    [
      1,
      10
    ],
    [
      11,
      20
    ],
    [
      21,
      30
    ],
    [
      31,
      40
    ],
    [
      41,
      50
    ],
    [
      51,
      60
    ],
    [
      61,
      70
    ],
    [
      71,
      80
    ],
    [
      81,
      90
    ],
    [
      91,
      100
    ],
    [
      101,
      110
    ],
    [
      111,
      125
    ]
  ];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("button", {
                children: JsxRuntime.jsxs("svg", {
                  children: [
                    JsxRuntime.jsx("path", {
                      d: "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z",
                      strokeLinecap: "round",
                      strokeLinejoin: "round",
                      strokeWidth: "2"
                    }),
                    JsxRuntime.jsx("path", {
                      d: "M15 12a3 3 0 11-6 0 3 3 0 016 0z",
                      strokeLinecap: "round",
                      strokeLinejoin: "round",
                      strokeWidth: "2"
                    })
                  ],
                  className: "w-5 h-5",
                  fill: "none",
                  stroke: "currentColor",
                  viewBox: "0 0 24 24"
                }),
                className: "p-2 text-gray-400 hover:text-gray-600 flex-shrink-0",
                title: "Settings",
                onClick: param => onSettings()
              }),
              className: "flex items-center gap-2 sm:gap-4 min-w-0"
            }),
            className: "sticky top-0 z-10 bg-white flex justify-between items-center py-4 px-4 sm:px-6 border-b border-gray-100 gap-2"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h1", {
                    children: "Learn Kirundi",
                    className: "text-4xl font-bold text-gray-900 mb-2"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "based off work from Elizabeth E. Cox.",
                    className: "text-gray-600"
                  })
                ],
                className: "text-center mb-8"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsxs("button", {
                  children: [
                    props.isStarted ? "Continue Lesson" : "Start Learning",
                    JsxRuntime.jsx("span", {
                      children: "→",
                      className: "ml-2 group-hover:translate-x-1 transition-transform"
                    })
                  ],
                  className: "group relative flex items-center justify-center px-8 py-4 bg-indigo-600 text-white text-xl font-bold rounded-2xl shadow-lg hover:bg-indigo-700 hover:-translate-y-1 transition-all",
                  onClick: param => onStart()
                }),
                className: "flex flex-col gap-4 w-full max-w-xs"
              })
            ],
            className: "flex flex-col items-center justify-center flex-grow px-4 pb-20"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: "View Lessons",
                className: "text-sm text-gray-400 font-medium mb-1"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("svg", {
                  children: JsxRuntime.jsx("path", {
                    d: "M19 9l-7 7-7-7",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "2"
                  }),
                  className: "w-5 h-5 text-gray-400",
                  fill: "none",
                  stroke: "currentColor",
                  viewBox: "0 0 24 24"
                }),
                className: "animate-bounce"
              })
            ],
            className: "absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-gray-50 to-transparent pointer-events-none flex flex-col items-center justify-end pb-4"
          })
        ],
        className: "relative flex flex-col min-h-screen"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx("button", {
                    children: "Introduction",
                    className: "p-4 flex items-center justify-center bg-white border border-gray-200 rounded-lg text-sm font-medium text-gray-600 hover:border-indigo-500 hover:text-indigo-600 hover:shadow-sm transition-all",
                    onClick: param => onLessonSelect(0)
                  }),
                  className: "grid grid-cols-2 sm:grid-cols-4 gap-2"
                }),
                className: "p-4 bg-gray-50/50 border-t border-gray-100"
              }),
              className: "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"
            }),
            lessonGroups.map((param, index) => {
              let startNum = param[0];
              return JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx("div", {
                    children: Stdlib_Array.fromInitializer((param[1] - startNum | 0) + 1 | 0, i => startNum + i | 0).map(n => JsxRuntime.jsx("button", {
                      children: n.toString(),
                      className: "aspect-square flex items-center justify-center bg-white border border-gray-200 rounded-lg text-sm font-medium text-gray-600 hover:border-indigo-500 hover:text-indigo-600 hover:shadow-sm transition-all",
                      onClick: param => onLessonSelect(n)
                    }, n.toString())),
                    className: "grid grid-cols-5 sm:grid-cols-10 gap-2"
                  }),
                  className: "p-4 bg-gray-50/50 border-t border-gray-100"
                }),
                className: "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"
              }, index.toString());
            })
          ],
          className: "flex flex-col gap-3"
        }),
        className: "px-4 py-12 bg-gray-50 min-h-screen"
      })
    ],
    className: "flex flex-col min-h-screen max-w-4xl mx-auto font-sans bg-gray-50"
  });
}

let make = MainMenu;

export {
  make,
}
/* react Not a pure module */
