// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function PracticeQuiz(props) {
  let onBack = props.onBack;
  let questions = props.questions;
  let match = React.useState(() => 0);
  let setCurrentIndex = match[1];
  let currentIndex = match[0];
  let match$1 = React.useState(() => 0);
  let setScore = match$1[1];
  let match$2 = React.useState(() => "Playing");
  let setGameState = match$2[1];
  let match$3 = React.useState(() => {});
  let setFeedback = match$3[1];
  let feedback = match$3[0];
  let options = React.useMemo(() => {
    let ctx = questions[currentIndex];
    if (ctx === undefined) {
      return [];
    }
    let correctAnswer = ctx.question.answer;
    let distractors = Stdlib_Array.toShuffled(ctx.sectionAnswers.filter(a => a !== correctAnswer)).slice(0, 3);
    return Stdlib_Array.toShuffled(distractors.concat([correctAnswer]));
  }, [currentIndex]);
  let tmp;
  if (match$2[0] === "Playing") {
    let ctx = Stdlib_Option.getExn(questions[currentIndex], undefined);
    let color = feedback !== undefined ? (
        feedback ? "#22c55e" : "#ef4444"
      ) : "transparent";
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: `Question ` + (currentIndex + 1 | 0).toString(),
          className: "mb-2 text-xs font-bold text-indigo-500 uppercase tracking-widest"
        }),
        JsxRuntime.jsx("h2", {
          children: ctx.question.prompt,
          className: "text-2xl font-bold text-gray-900 mb-8"
        }),
        JsxRuntime.jsx("div", {
          children: options.map(opt => JsxRuntime.jsx("button", {
            children: opt,
            className: "w-full text-left p-4 rounded-xl border-2 border-gray-100 hover:border-indigo-500 transition-all font-medium text-gray-700",
            disabled: Stdlib_Option.isSome(feedback),
            onClick: param => {
              let ctx = questions[currentIndex];
              let isCorrect = Stdlib_Option.mapOr(ctx, false, c => c.question.answer === opt);
              setFeedback(param => isCorrect);
              if (isCorrect) {
                setScore(prev => prev + 1 | 0);
              }
              setTimeout(() => {
                setFeedback(param => {});
                if (currentIndex < (questions.length - 1 | 0)) {
                  return setCurrentIndex(prev => prev + 1 | 0);
                } else {
                  return setGameState(param => "Finished");
                }
              }, 600);
            }
          }, opt)),
          className: "grid gap-3"
        })
      ],
      className: "bg-white rounded-3xl shadow-xl p-8 border-4 transition-colors duration-200",
      style: {
        borderColor: color
      }
    });
  } else {
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: "🎉",
          className: "text-5xl mb-4"
        }),
        JsxRuntime.jsx("h2", {
          children: "Quiz Complete!",
          className: "text-2xl font-bold mb-2"
        }),
        JsxRuntime.jsx("p", {
          children: `You got ` + match$1[0].toString() + ` out of ` + questions.length.toString() + ` correct.`,
          className: "text-gray-600 mb-6"
        }),
        JsxRuntime.jsx("button", {
          children: "Return to Menu",
          className: "w-full py-4 bg-indigo-600 text-white rounded-xl font-bold shadow-lg",
          onClick: param => onBack()
        })
      ],
      className: "p-8 text-center"
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "← Back to Menu",
        className: "mb-8 text-indigo-600 font-medium flex items-center gap-2",
        onClick: param => onBack()
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "max-w-md mx-auto w-full"
      })
    ],
    className: "flex flex-col min-h-screen bg-gray-50 p-4"
  });
}

let make = PracticeQuiz;

export {
  make,
}
/* react Not a pure module */
