// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function PracticeQuiz(props) {
  let onBack = props.onBack;
  let questions = props.questions;
  let match = React.useState(() => 0);
  let setCurrentIndex = match[1];
  let currentIndex = match[0];
  let match$1 = React.useState(() => 0);
  let setScore = match$1[1];
  let match$2 = React.useState(() => "Playing");
  let setGameState = match$2[1];
  let match$3 = React.useState(() => {});
  let setSelectedChoice = match$3[1];
  let selectedChoice = match$3[0];
  let shuffledQuestions = React.useMemo(() => Stdlib_Array.toShuffled(questions), [questions]);
  let currentQuestion = shuffledQuestions[currentIndex];
  let options = React.useMemo(() => {
    if (currentQuestion === undefined) {
      return [];
    }
    let correctAnswer = currentQuestion.question.answer;
    let distractors = Stdlib_Array.toShuffled(currentQuestion.sectionAnswers.filter(a => a !== correctAnswer)).slice(0, 3);
    return Stdlib_Array.toShuffled(distractors.concat([correctAnswer]));
  }, [
    currentIndex,
    shuffledQuestions
  ]);
  let tmp;
  if (match$2[0] === "Playing") {
    let ctx = Stdlib_Option.getExn(currentQuestion, undefined);
    let correctAnswer = ctx.question.answer;
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: `Question ` + (currentIndex + 1 | 0).toString(),
          className: "mb-2 text-xs font-bold text-indigo-500 uppercase tracking-widest"
        }),
        JsxRuntime.jsx("h2", {
          children: ctx.question.prompt,
          className: "text-2xl font-bold text-gray-900 mb-8"
        }),
        JsxRuntime.jsx("div", {
          children: options.map(opt => {
            let isSelected = Primitive_object.equal(selectedChoice, opt);
            let hasAnswered = Stdlib_Option.isSome(selectedChoice);
            let isCorrect = opt === correctAnswer;
            let isWrongSelection = isSelected && !isCorrect;
            let buttonStyles = hasAnswered ? (
                isCorrect ? "bg-green-500 border-green-500 text-white shadow-lg" : (
                    isWrongSelection ? "bg-red-500 border-red-500 text-white animate-shake shadow-inner" : "bg-gray-50 border-gray-100 text-gray-400 opacity-50"
                  )
              ) : "bg-white border-gray-100 text-gray-700 hover:border-indigo-500 hover:shadow-md";
            return JsxRuntime.jsx("button", {
              children: opt,
              className: `w-full text-left p-4 rounded-xl border-2 transition-all duration-200 font-medium ` + buttonStyles,
              disabled: hasAnswered,
              onClick: param => {
                let isCorrect = Stdlib_Option.mapOr(currentQuestion, false, c => c.question.answer === opt);
                setSelectedChoice(param => opt);
                if (isCorrect) {
                  setScore(prev => prev + 1 | 0);
                }
                setTimeout(() => {
                  setSelectedChoice(param => {});
                  if (currentIndex < (shuffledQuestions.length - 1 | 0)) {
                    return setCurrentIndex(prev => prev + 1 | 0);
                  } else {
                    return setGameState(param => "Finished");
                  }
                }, 1000);
              }
            }, opt);
          }),
          className: "grid gap-3"
        })
      ],
      className: "bg-white rounded-3xl shadow-xl p-8 border-4 border-transparent"
    });
  } else {
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h2", {
          children: "Quiz Complete!",
          className: "text-2xl font-bold mb-2"
        }),
        JsxRuntime.jsx("p", {
          children: `Score: ` + match$1[0].toString() + `/` + shuffledQuestions.length.toString(),
          className: "text-gray-600 mb-6"
        }),
        JsxRuntime.jsx("button", {
          children: "Return to Menu",
          className: "w-full py-4 bg-indigo-600 text-white rounded-xl font-bold shadow-lg",
          onClick: param => onBack()
        })
      ],
      className: "p-8 text-center"
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "← Back to Menu",
        className: "mb-8 text-indigo-600 font-medium flex items-center gap-2",
        onClick: param => onBack()
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "max-w-md mx-auto w-full"
      })
    ],
    className: "flex flex-col min-h-screen bg-gray-50 p-4"
  });
}

let make = PracticeQuiz;

export {
  make,
}
/* react Not a pure module */
