// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Quiz$QuizQuestionView(props) {
  let question = props.question;
  let match = React.useState(() => "");
  let setUserInput = match[1];
  let userInput = match[0];
  let match$1 = React.useState(() => false);
  let setChecked = match$1[1];
  let feedback = (ok, text) => JsxRuntime.jsx("p", {
    children: text,
    className: "mt-2 text-sm font-bold italic " + (
      ok ? "text-green-800" : "text-red-800"
    )
  });
  let answer = question.answer;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("span", {
          children: (props.index + 1 | 0).toString() + ".",
          className: "font-bold"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              JsxRuntime.jsx("p", {
                children: question.prompt,
                className: "text-justify leading-normal"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("input", {
                    className: "flex-1 border-b border-black py-1 focus:outline-none focus:bg-gray-50 bg-transparent",
                    placeholder: "Type answer here...",
                    value: userInput,
                    onChange: e => setUserInput(param => e.target.value)
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Check",
                    className: "border border-black px-4 py-1 text-sm font-bold uppercase hover:bg-black hover:text-white transition-colors",
                    onClick: param => setChecked(param => true)
                  })
                ],
                className: "flex flex-col sm:flex-row gap-2"
              }),
              match$1[0] ? feedback(userInput === answer, userInput === answer ? "✓ Correct" : "✗ Correct answer: " + answer) : null
            ]
          }),
          className: "flex-1 space-y-4"
        })
      ],
      className: "flex gap-x-4"
    }),
    className: "py-6 border-b border-gray-200 last:border-0 font-serif text-[11pt]"
  });
}

let QuizQuestionView = {
  make: Quiz$QuizQuestionView
};

function Quiz(props) {
  let section = props.section;
  return JsxRuntime.jsxs("section", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("h3", {
          children: section.title,
          className: "text-center font-bold uppercase text-lg tracking-tight"
        }),
        className: "border-b border-black pb-1 mb-4"
      }),
      JsxRuntime.jsx("div", {
        children: section.questions.map((q, i) => JsxRuntime.jsx(Quiz$QuizQuestionView, {
          question: q,
          index: i
        }, i.toString())),
        className: "divide-y divide-gray-100"
      })
    ],
    className: "max-w-3xl mx-auto p-8 bg-white font-serif text-black border-t-2 border-black mt-8"
  });
}

let make = Quiz;

export {
  QuizQuestionView,
  make,
}
/* react Not a pure module */
