// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function Quiz$QuizQuestionView(props) {
  let question = props.question;
  let match = React.useState(() => "");
  let setUserInput = match[1];
  let userInput = match[0];
  let match$1 = React.useState(() => -1);
  let setSelected = match$1[1];
  let selected = match$1[0];
  let match$2 = React.useState(() => false);
  let setChecked = match$2[1];
  let checked = match$2[0];
  let feedback = (ok, text) => JsxRuntime.jsx("p", {
    children: text,
    className: "mt-2 text-sm font-bold italic " + (
      ok ? "text-green-800" : "text-red-800"
    )
  });
  let tmp;
  if (question.TAG === "TextInput") {
    let answer = question.answer;
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsx("p", {
          children: question.prompt,
          className: "text-justify leading-normal"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "flex-1 border-b border-black py-1 focus:outline-none focus:bg-gray-50 bg-transparent",
              placeholder: "Type answer here...",
              value: userInput,
              onChange: e => setUserInput(param => e.target.value)
            }),
            JsxRuntime.jsx("button", {
              children: "Check",
              className: "border border-black px-4 py-1 text-sm font-bold uppercase hover:bg-black hover:text-white transition-colors",
              onClick: param => setChecked(param => true)
            })
          ],
          className: "flex flex-col sm:flex-row gap-2"
        }),
        checked ? feedback(userInput === answer, userInput === answer ? "✓ Correct" : "✗ Correct answer: " + answer) : null
      ]
    });
  } else {
    let correctIndex = question.correctIndex;
    let options = question.options;
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsx("p", {
          children: question.prompt,
          className: "text-justify leading-normal"
        }),
        JsxRuntime.jsx("ul", {
          children: options.map((opt, i) => JsxRuntime.jsxs("li", {
            children: [
              JsxRuntime.jsx("input", {
                className: "accent-black h-4 w-4",
                checked: selected === i,
                type: "radio",
                onChange: param => setSelected(param => i)
              }),
              JsxRuntime.jsx("span", {
                children: opt,
                className: "cursor-pointer",
                onClick: param => setSelected(param => i)
              })
            ],
            className: "flex items-center gap-3"
          }, i.toString())),
          className: "space-y-2 mt-2"
        }),
        JsxRuntime.jsx("button", {
          children: "Check",
          className: "mt-2 border border-black px-4 py-1 text-sm font-bold uppercase hover:bg-black hover:text-white transition-colors",
          onClick: param => setChecked(param => true)
        }),
        checked ? feedback(selected === correctIndex, selected === correctIndex ? "✓ Correct" : "✗ Correct answer: " + Stdlib_Option.getOr(options[correctIndex], "error")) : null
      ]
    });
  }
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("span", {
          children: (props.index + 1 | 0).toString() + ".",
          className: "font-bold"
        }),
        JsxRuntime.jsx("div", {
          children: tmp,
          className: "flex-1 space-y-4"
        })
      ],
      className: "flex gap-x-4"
    }),
    className: "py-6 border-b border-gray-200 last:border-0 font-serif text-[11pt]"
  });
}

let QuizQuestionView = {
  make: Quiz$QuizQuestionView
};

function Quiz(props) {
  let section = props.section;
  return JsxRuntime.jsxs("section", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("h3", {
          children: section.title,
          className: "text-center font-bold uppercase text-lg tracking-tight"
        }),
        className: "border-b border-black pb-1 mb-4"
      }),
      JsxRuntime.jsx("div", {
        children: section.questions.map((q, i) => JsxRuntime.jsx(Quiz$QuizQuestionView, {
          question: q,
          index: i
        }, i.toString())),
        className: "divide-y divide-gray-100"
      })
    ],
    className: "max-w-3xl mx-auto p-8 bg-white font-serif text-black border-t-2 border-black mt-8"
  });
}

let make = Quiz;

export {
  QuizQuestionView,
  make,
}
/* react Not a pure module */
