// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Settings(props) {
  let onReset = props.onReset;
  let onBack = props.onBack;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "← Back to Menu",
        className: "mb-8 text-gray-500 hover:text-gray-800 flex items-center text-sm font-medium",
        onClick: param => onBack()
      }),
      JsxRuntime.jsx("h2", {
        children: "Settings",
        className: "text-3xl font-bold text-gray-900 mb-6"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h3", {
                  children: "Learning Progress",
                  className: "font-semibold text-gray-900"
                }),
                JsxRuntime.jsx("p", {
                  children: "Reset all your completed lessons and start from the beginning.",
                  className: "text-sm text-gray-500"
                })
              ]
            }),
            JsxRuntime.jsx("button", {
              children: "Reset Progress",
              className: "bg-red-50 text-red-600 hover:bg-red-100 px-4 py-2 rounded-lg font-medium transition-colors",
              onClick: param => onReset()
            })
          ],
          className: "p-6 border-b border-gray-100 flex justify-between items-center"
        }),
        className: "bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden"
      })
    ],
    className: "flex flex-col min-h-screen bg-gray-50 p-6 max-w-2xl mx-auto"
  });
}

let make = Settings;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
