// Generated by ReScript, PLEASE EDIT WITH CARE


function calculateNextReview(stats, result) {
  let now = Date.now();
  switch (result) {
    case "Again" :
      return {
        lastReviewed: now,
        interval: 0.0,
        easeFactor: Math.max(1.3, stats.easeFactor - 0.2)
      };
    case "Hard" :
      return {
        lastReviewed: now,
        interval: Math.max(1.0, stats.interval * 1.2),
        easeFactor: Math.max(1.3, stats.easeFactor - 0.15)
      };
    case "Good" :
      return {
        lastReviewed: now,
        interval: stats.interval === 0.0 ? 1.0 : stats.interval * stats.easeFactor,
        easeFactor: stats.easeFactor
      };
    case "Easy" :
      return {
        lastReviewed: now,
        interval: stats.interval === 0.0 ? 4.0 : stats.interval * (stats.easeFactor + 0.15),
        easeFactor: stats.easeFactor + 0.15
      };
  }
}

let defaultStats = {
  lastReviewed: 0.0,
  interval: 0.0,
  easeFactor: 2.5
};

export {
  defaultStats,
  calculateNextReview,
}
/* No side effect */
